import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

getGoogleFont(String fontString) {
  try {
    return fontString.isNotEmpty ? baoFontList.firstWhere((element) => element.label == fontString).font : GoogleFonts.roboto();
  } catch (e) {
    return GoogleFonts.roboto();
  }
}

class BaoFontList {
  BaoFontList({
    required this.font,
    required this.label,
  });

  TextStyle font;
  String label;
}

List<BaoFontList> baoFontList = [
  BaoFontList(label: 'ABeeZee', font: GoogleFonts.aBeeZee()),
  BaoFontList(label: 'Abel', font: GoogleFonts.abel()),
  BaoFontList(label: 'Abhaya Libre', font: GoogleFonts.abhayaLibre()),
  BaoFontList(label: 'Abril Fatface', font: GoogleFonts.abrilFatface()),
  BaoFontList(label: 'Aclonica', font: GoogleFonts.aclonica()),
  BaoFontList(label: 'Acme', font: GoogleFonts.acme()),
  BaoFontList(label: 'Actor', font: GoogleFonts.actor()),
  BaoFontList(label: 'Adamina', font: GoogleFonts.adamina()),
  BaoFontList(label: 'Advent Pro', font: GoogleFonts.adventPro()),
  BaoFontList(label: 'Aguafina Script', font: GoogleFonts.aguafinaScript()),
  BaoFontList(label: 'Akaya Telivigala', font: GoogleFonts.akayaTelivigala()),
  BaoFontList(label: 'Akronim', font: GoogleFonts.akronim()),
  BaoFontList(label: 'Aladin', font: GoogleFonts.aladin()),
  BaoFontList(label: 'Alata', font: GoogleFonts.alata()),
  BaoFontList(label: 'Alatsi', font: GoogleFonts.alatsi()),
  BaoFontList(label: 'Aldrich', font: GoogleFonts.aldrich()),
  BaoFontList(label: 'Alef', font: GoogleFonts.alef()),
  BaoFontList(label: 'Alegreya', font: GoogleFonts.alegreya()),
  BaoFontList(label: 'Alegreya SC', font: GoogleFonts.alegreyaSc()),
  BaoFontList(label: 'Alegreya Sans', font: GoogleFonts.alegreyaSans()),
  BaoFontList(label: 'Alegreya Sans SC', font: GoogleFonts.alegreyaSansSc()),
  BaoFontList(label: 'Aleo', font: GoogleFonts.aleo()),
  BaoFontList(label: 'Alex Brush', font: GoogleFonts.alexBrush()),
  BaoFontList(label: 'Alfa Slab One', font: GoogleFonts.alfaSlabOne()),
  BaoFontList(label: 'Alice', font: GoogleFonts.alice()),
  BaoFontList(label: 'Alike', font: GoogleFonts.alike()),
  BaoFontList(label: 'Alike Angular', font: GoogleFonts.alikeAngular()),
  BaoFontList(label: 'Allan', font: GoogleFonts.allan()),
  BaoFontList(label: 'Allerta', font: GoogleFonts.allerta()),
  BaoFontList(label: 'Allerta Stencil', font: GoogleFonts.allertaStencil()),
  BaoFontList(label: 'Allison', font: GoogleFonts.allison()),
  BaoFontList(label: 'Allura', font: GoogleFonts.allura()),
  BaoFontList(label: 'Almarai', font: GoogleFonts.almarai()),
  BaoFontList(label: 'Almendra', font: GoogleFonts.almendra()),
  BaoFontList(label: 'Almendra Display', font: GoogleFonts.almendraDisplay()),
  BaoFontList(label: 'Almendra SC', font: GoogleFonts.almendraSc()),
  BaoFontList(label: 'Alumni Sans', font: GoogleFonts.alumniSans()),
  BaoFontList(label: 'Amarante', font: GoogleFonts.amarante()),
  BaoFontList(label: 'Amaranth', font: GoogleFonts.amaranth()),
  BaoFontList(label: 'Amatic SC', font: GoogleFonts.amaticSc()),
  BaoFontList(label: 'Amatica SC', font: GoogleFonts.amaticaSc()),
  BaoFontList(label: 'Amethysta', font: GoogleFonts.amethysta()),
  BaoFontList(label: 'Amiko', font: GoogleFonts.amiko()),
  BaoFontList(label: 'Amiri', font: GoogleFonts.amiri()),
  BaoFontList(label: 'Amita', font: GoogleFonts.amita()),
  BaoFontList(label: 'Anaheim', font: GoogleFonts.anaheim()),
  BaoFontList(label: 'Andada', font: GoogleFonts.andada()),
  BaoFontList(label: 'Andada Pro', font: GoogleFonts.andadaPro()),
  BaoFontList(label: 'Andika', font: GoogleFonts.andika()),
  BaoFontList(label: 'Andika New Basic', font: GoogleFonts.andikaNewBasic()),
  BaoFontList(label: 'Annie Use Your Telescope', font: GoogleFonts.annieUseYourTelescope()),
  BaoFontList(label: 'Anonymous Pro', font: GoogleFonts.anonymousPro()),
  BaoFontList(label: 'Antic', font: GoogleFonts.antic()),
  BaoFontList(label: 'Antic Didone', font: GoogleFonts.anticDidone()),
  BaoFontList(label: 'Antic Slab', font: GoogleFonts.anticSlab()),
  BaoFontList(label: 'Anton', font: GoogleFonts.anton()),
  BaoFontList(label: 'Arapey', font: GoogleFonts.arapey()),
  BaoFontList(label: 'Arbutus', font: GoogleFonts.arbutus()),
  BaoFontList(label: 'Arbutus Slab', font: GoogleFonts.arbutusSlab()),
  BaoFontList(label: 'Architects Daughter', font: GoogleFonts.architectsDaughter()),
  BaoFontList(label: 'Archivo', font: GoogleFonts.archivo()),
  BaoFontList(label: 'Archivo Black', font: GoogleFonts.archivoBlack()),
  BaoFontList(label: 'Archivo Narrow', font: GoogleFonts.archivoNarrow()),
  BaoFontList(label: 'Are You Serious', font: GoogleFonts.areYouSerious()),
  BaoFontList(label: 'Aref Ruqaa', font: GoogleFonts.arefRuqaa()),
  BaoFontList(label: 'Arima Madurai', font: GoogleFonts.arimaMadurai()),
  BaoFontList(label: 'Arimo', font: GoogleFonts.arimo()),
  BaoFontList(label: 'Arizonia', font: GoogleFonts.arizonia()),
  BaoFontList(label: 'Armata', font: GoogleFonts.armata()),
  BaoFontList(label: 'Arsenal', font: GoogleFonts.arsenal()),
  BaoFontList(label: 'Artifika', font: GoogleFonts.artifika()),
  BaoFontList(label: 'Arvo', font: GoogleFonts.arvo()),
  BaoFontList(label: 'Arya', font: GoogleFonts.arya()),
  BaoFontList(label: 'Asap', font: GoogleFonts.asap()),
  BaoFontList(label: 'Asar', font: GoogleFonts.asar()),
  BaoFontList(label: 'Asset', font: GoogleFonts.asset()),
  BaoFontList(label: 'Assistant', font: GoogleFonts.assistant()),
  BaoFontList(label: 'Astloch', font: GoogleFonts.astloch()),
  BaoFontList(label: 'Asul', font: GoogleFonts.asul()),
  BaoFontList(label: 'Athiti', font: GoogleFonts.athiti()),
  BaoFontList(label: 'Atkinson Hyperlegible', font: GoogleFonts.atkinsonHyperlegible()),
  BaoFontList(label: 'Atma', font: GoogleFonts.atma()),
  BaoFontList(label: 'Atomic Age', font: GoogleFonts.atomicAge()),
  BaoFontList(label: 'Aubrey', font: GoogleFonts.aubrey()),
  BaoFontList(label: 'Audiowide', font: GoogleFonts.audiowide()),
  BaoFontList(label: 'Autour One', font: GoogleFonts.autourOne()),
  BaoFontList(label: 'Average', font: GoogleFonts.average()),
  BaoFontList(label: 'Average Sans', font: GoogleFonts.averageSans()),
  BaoFontList(label: 'Averia Gruesa Libre', font: GoogleFonts.averiaGruesaLibre()),
  BaoFontList(label: 'Averia Libre', font: GoogleFonts.averiaLibre()),
  BaoFontList(label: 'Averia Sans Libre', font: GoogleFonts.averiaSansLibre()),
  BaoFontList(label: 'Averia Serif Libre', font: GoogleFonts.averiaSerifLibre()),
  BaoFontList(label: 'Azeret Mono', font: GoogleFonts.azeretMono()),
  BaoFontList(label: 'B612', font: GoogleFonts.b612()),
  BaoFontList(label: 'B612 Mono', font: GoogleFonts.b612Mono()),
  BaoFontList(label: 'Bad Script', font: GoogleFonts.badScript()),
  BaoFontList(label: 'Bahiana', font: GoogleFonts.bahiana()),
  BaoFontList(label: 'Bahianita', font: GoogleFonts.bahianita()),
  BaoFontList(label: 'Bai Jamjuree', font: GoogleFonts.baiJamjuree()),
  BaoFontList(label: 'Bakbak One', font: GoogleFonts.bakbakOne()),
  BaoFontList(label: 'Baloo', font: GoogleFonts.baloo()),
  BaoFontList(label: 'Baloo 2', font: GoogleFonts.baloo2()),
  BaoFontList(label: 'Baloo Bhai', font: GoogleFonts.balooBhai()),
  BaoFontList(label: 'Baloo Bhai 2', font: GoogleFonts.balooBhai2()),
  BaoFontList(label: 'Baloo Bhaijaan', font: GoogleFonts.balooBhaijaan()),
  BaoFontList(label: 'Baloo Bhaijaan 2', font: GoogleFonts.balooBhaijaan2()),
  BaoFontList(label: 'Baloo Bhaina', font: GoogleFonts.balooBhaina()),
  BaoFontList(label: 'Baloo Bhaina 2', font: GoogleFonts.balooBhaina2()),
  BaoFontList(label: 'Baloo Chettan', font: GoogleFonts.balooChettan()),
  BaoFontList(label: 'Baloo Chettan 2', font: GoogleFonts.balooChettan2()),
  BaoFontList(label: 'Baloo Da', font: GoogleFonts.balooDa()),
  BaoFontList(label: 'Baloo Da 2', font: GoogleFonts.balooDa2()),
  BaoFontList(label: 'Baloo Paaji', font: GoogleFonts.balooPaaji()),
  BaoFontList(label: 'Baloo Paaji 2', font: GoogleFonts.balooPaaji2()),
  BaoFontList(label: 'Baloo Tamma', font: GoogleFonts.balooTamma()),
  BaoFontList(label: 'Baloo Tamma 2', font: GoogleFonts.balooTamma2()),
  BaoFontList(label: 'Baloo Tammudu', font: GoogleFonts.balooTammudu()),
  BaoFontList(label: 'Baloo Tammudu 2', font: GoogleFonts.balooTammudu2()),
  BaoFontList(label: 'Baloo Thambi', font: GoogleFonts.balooThambi()),
  BaoFontList(label: 'Baloo Thambi 2', font: GoogleFonts.balooThambi2()),
  BaoFontList(label: 'Balsamiq Sans', font: GoogleFonts.balsamiqSans()),
  BaoFontList(label: 'Balthazar', font: GoogleFonts.balthazar()),
  BaoFontList(label: 'Bangers', font: GoogleFonts.bangers()),
  BaoFontList(label: 'Barlow', font: GoogleFonts.barlow()),
  BaoFontList(label: 'Barlow Condensed', font: GoogleFonts.barlowCondensed()),
  BaoFontList(label: 'Barlow Semi Condensed', font: GoogleFonts.barlowSemiCondensed()),
  BaoFontList(label: 'Barriecito', font: GoogleFonts.barriecito()),
  BaoFontList(label: 'Barrio', font: GoogleFonts.barrio()),
  BaoFontList(label: 'Basic', font: GoogleFonts.basic()),
  BaoFontList(label: 'Baskervville', font: GoogleFonts.baskervville()),
  BaoFontList(label: 'Baumans', font: GoogleFonts.baumans()),
  BaoFontList(label: 'Be Vietnam', font: GoogleFonts.beVietnam()),
  BaoFontList(label: 'Be Vietnam Pro', font: GoogleFonts.beVietnamPro()),
  BaoFontList(label: 'Bebas Neue', font: GoogleFonts.bebasNeue()),
  BaoFontList(label: 'Belgrano', font: GoogleFonts.belgrano()),
  BaoFontList(label: 'Bellefair', font: GoogleFonts.bellefair()),
  BaoFontList(label: 'Belleza', font: GoogleFonts.belleza()),
  BaoFontList(label: 'Bellota', font: GoogleFonts.bellota()),
  BaoFontList(label: 'Bellota Text', font: GoogleFonts.bellotaText()),
  BaoFontList(label: 'BenchNine', font: GoogleFonts.benchNine()),
  BaoFontList(label: 'Bentham', font: GoogleFonts.bentham()),
  BaoFontList(label: 'Berkshire Swash', font: GoogleFonts.berkshireSwash()),
  BaoFontList(label: 'Besley', font: GoogleFonts.besley()),
  BaoFontList(label: 'Beth Ellen', font: GoogleFonts.bethEllen()),
  BaoFontList(label: 'Bevan', font: GoogleFonts.bevan()),
  BaoFontList(label: 'Big Shoulders Display', font: GoogleFonts.bigShouldersDisplay()),
  BaoFontList(label: 'Big Shoulders Inline Display', font: GoogleFonts.bigShouldersInlineDisplay()),
  BaoFontList(label: 'Big Shoulders Inline Text', font: GoogleFonts.bigShouldersInlineText()),
  BaoFontList(label: 'Big Shoulders Stencil Display', font: GoogleFonts.bigShouldersStencilDisplay()),
  BaoFontList(label: 'Big Shoulders Stencil Text', font: GoogleFonts.bigShouldersStencilText()),
  BaoFontList(label: 'Big Shoulders Text', font: GoogleFonts.bigShouldersText()),
  BaoFontList(label: 'Bigelow Rules', font: GoogleFonts.bigelowRules()),
  BaoFontList(label: 'Bigshot One', font: GoogleFonts.bigshotOne()),
  BaoFontList(label: 'Bilbo', font: GoogleFonts.bilbo()),
  BaoFontList(label: 'Bilbo Swash Caps', font: GoogleFonts.bilboSwashCaps()),
  BaoFontList(label: 'BioRhyme', font: GoogleFonts.bioRhyme()),
  BaoFontList(label: 'BioRhyme Expanded', font: GoogleFonts.bioRhymeExpanded()),
  BaoFontList(label: 'Birthstone', font: GoogleFonts.birthstone()),
  BaoFontList(label: 'Birthstone Bounce', font: GoogleFonts.birthstoneBounce()),
  BaoFontList(label: 'Biryani', font: GoogleFonts.biryani()),
  BaoFontList(label: 'Bitter', font: GoogleFonts.bitter()),
  BaoFontList(label: 'Black And White Picture', font: GoogleFonts.blackAndWhitePicture()),
  BaoFontList(label: 'Black Han Sans', font: GoogleFonts.blackHanSans()),
  BaoFontList(label: 'Black Ops One', font: GoogleFonts.blackOpsOne()),
  BaoFontList(label: 'Blinker', font: GoogleFonts.blinker()),
  BaoFontList(label: 'Bona Nova', font: GoogleFonts.bonaNova()),
  BaoFontList(label: 'Bonbon', font: GoogleFonts.bonbon()),
  BaoFontList(label: 'Bonheur Royale', font: GoogleFonts.bonheurRoyale()),
  BaoFontList(label: 'Boogaloo', font: GoogleFonts.boogaloo()),
  BaoFontList(label: 'Bowlby One', font: GoogleFonts.bowlbyOne()),
  BaoFontList(label: 'Bowlby One SC', font: GoogleFonts.bowlbyOneSc()),
  BaoFontList(label: 'Brawler', font: GoogleFonts.brawler()),
  BaoFontList(label: 'Bree Serif', font: GoogleFonts.breeSerif()),
  BaoFontList(label: 'Brygada 1918', font: GoogleFonts.brygada1918()),
  BaoFontList(label: 'Bubblegum Sans', font: GoogleFonts.bubblegumSans()),
  BaoFontList(label: 'Bubbler One', font: GoogleFonts.bubblerOne()),
  BaoFontList(label: 'Buda', font: GoogleFonts.buda()),
  BaoFontList(label: 'Buenard', font: GoogleFonts.buenard()),
  BaoFontList(label: 'Bungee', font: GoogleFonts.bungee()),
  BaoFontList(label: 'Bungee Hairline', font: GoogleFonts.bungeeHairline()),
  BaoFontList(label: 'Bungee Inline', font: GoogleFonts.bungeeInline()),
  BaoFontList(label: 'Bungee Outline', font: GoogleFonts.bungeeOutline()),
  BaoFontList(label: 'Bungee Shade', font: GoogleFonts.bungeeShade()),
  BaoFontList(label: 'Butcherman', font: GoogleFonts.butcherman()),
  BaoFontList(label: 'Butterfly Kids', font: GoogleFonts.butterflyKids()),
  BaoFontList(label: 'Cabin', font: GoogleFonts.cabin()),
  BaoFontList(label: 'Cabin Condensed', font: GoogleFonts.cabinCondensed()),
  BaoFontList(label: 'Cabin Sketch', font: GoogleFonts.cabinSketch()),
  BaoFontList(label: 'Caesar Dressing', font: GoogleFonts.caesarDressing()),
  BaoFontList(label: 'Cagliostro', font: GoogleFonts.cagliostro()),
  BaoFontList(label: 'Cairo', font: GoogleFonts.cairo()),
  BaoFontList(label: 'Caladea', font: GoogleFonts.caladea()),
  BaoFontList(label: 'Calistoga', font: GoogleFonts.calistoga()),
  BaoFontList(label: 'Calligraffitti', font: GoogleFonts.calligraffitti()),
  BaoFontList(label: 'Cambay', font: GoogleFonts.cambay()),
  BaoFontList(label: 'Cambo', font: GoogleFonts.cambo()),
  BaoFontList(label: 'Candal', font: GoogleFonts.candal()),
  BaoFontList(label: 'Cantarell', font: GoogleFonts.cantarell()),
  BaoFontList(label: 'Cantata One', font: GoogleFonts.cantataOne()),
  BaoFontList(label: 'Cantora One', font: GoogleFonts.cantoraOne()),
  BaoFontList(label: 'Capriola', font: GoogleFonts.capriola()),
  BaoFontList(label: 'Caramel', font: GoogleFonts.caramel()),
  BaoFontList(label: 'Carattere', font: GoogleFonts.carattere()),
  BaoFontList(label: 'Cardo', font: GoogleFonts.cardo()),
  BaoFontList(label: 'Carme', font: GoogleFonts.carme()),
  BaoFontList(label: 'Carrois Gothic', font: GoogleFonts.carroisGothic()),
  BaoFontList(label: 'Carrois Gothic SC', font: GoogleFonts.carroisGothicSc()),
  BaoFontList(label: 'Carter One', font: GoogleFonts.carterOne()),
  BaoFontList(label: 'Castoro', font: GoogleFonts.castoro()),
  BaoFontList(label: 'Catamaran', font: GoogleFonts.catamaran()),
  BaoFontList(label: 'Caudex', font: GoogleFonts.caudex()),
  BaoFontList(label: 'Caveat', font: GoogleFonts.caveat()),
  BaoFontList(label: 'Caveat Brush', font: GoogleFonts.caveatBrush()),
  BaoFontList(label: 'Cedarville Cursive', font: GoogleFonts.cedarvilleCursive()),
  BaoFontList(label: 'Ceviche One', font: GoogleFonts.cevicheOne()),
  BaoFontList(label: 'Chakra Petch', font: GoogleFonts.chakraPetch()),
  BaoFontList(label: 'Changa', font: GoogleFonts.changa()),
  BaoFontList(label: 'Changa One', font: GoogleFonts.changaOne()),
  BaoFontList(label: 'Chango', font: GoogleFonts.chango()),
  BaoFontList(label: 'Charm', font: GoogleFonts.charm()),
  BaoFontList(label: 'Charmonman', font: GoogleFonts.charmonman()),
  BaoFontList(label: 'Chathura', font: GoogleFonts.chathura()),
  BaoFontList(label: 'Chau Philomene One', font: GoogleFonts.chauPhilomeneOne()),
  BaoFontList(label: 'Chela One', font: GoogleFonts.chelaOne()),
  BaoFontList(label: 'Chelsea Market', font: GoogleFonts.chelseaMarket()),
  BaoFontList(label: 'Cherish', font: GoogleFonts.cherish()),
  BaoFontList(label: 'Cherry Cream Soda', font: GoogleFonts.cherryCreamSoda()),
  BaoFontList(label: 'Cherry Swash', font: GoogleFonts.cherrySwash()),
  BaoFontList(label: 'Chewy', font: GoogleFonts.chewy()),
  BaoFontList(label: 'Chicle', font: GoogleFonts.chicle()),
  BaoFontList(label: 'Chilanka', font: GoogleFonts.chilanka()),
  BaoFontList(label: 'Chivo', font: GoogleFonts.chivo()),
  BaoFontList(label: 'Chonburi', font: GoogleFonts.chonburi()),
  BaoFontList(label: 'Cinzel', font: GoogleFonts.cinzel()),
  BaoFontList(label: 'Cinzel Decorative', font: GoogleFonts.cinzelDecorative()),
  BaoFontList(label: 'Clicker Script', font: GoogleFonts.clickerScript()),
  BaoFontList(label: 'Coda', font: GoogleFonts.coda()),
  BaoFontList(label: 'Coda Caption', font: GoogleFonts.codaCaption()),
  BaoFontList(label: 'Codystar', font: GoogleFonts.codystar()),
  BaoFontList(label: 'Coiny', font: GoogleFonts.coiny()),
  BaoFontList(label: 'Combo', font: GoogleFonts.combo()),
  BaoFontList(label: 'Comfortaa', font: GoogleFonts.comfortaa()),
  BaoFontList(label: 'Comforter', font: GoogleFonts.comforter()),
  BaoFontList(label: 'Comforter Brush', font: GoogleFonts.comforterBrush()),
  BaoFontList(label: 'Comic Neue', font: GoogleFonts.comicNeue()),
  BaoFontList(label: 'Coming Soon', font: GoogleFonts.comingSoon()),
  BaoFontList(label: 'Commissioner', font: GoogleFonts.commissioner()),
  BaoFontList(label: 'Concert One', font: GoogleFonts.concertOne()),
  BaoFontList(label: 'Condiment', font: GoogleFonts.condiment()),
  BaoFontList(label: 'Contrail One', font: GoogleFonts.contrailOne()),
  BaoFontList(label: 'Convergence', font: GoogleFonts.convergence()),
  BaoFontList(label: 'Cookie', font: GoogleFonts.cookie()),
  BaoFontList(label: 'Copse', font: GoogleFonts.copse()),
  BaoFontList(label: 'Corben', font: GoogleFonts.corben()),
  BaoFontList(label: 'Corinthia', font: GoogleFonts.corinthia()),
  BaoFontList(label: 'Cormorant', font: GoogleFonts.cormorant()),
  BaoFontList(label: 'Cormorant Garamond', font: GoogleFonts.cormorantGaramond()),
  BaoFontList(label: 'Cormorant Infant', font: GoogleFonts.cormorantInfant()),
  BaoFontList(label: 'Cormorant SC', font: GoogleFonts.cormorantSc()),
  BaoFontList(label: 'Cormorant Unicase', font: GoogleFonts.cormorantUnicase()),
  BaoFontList(label: 'Cormorant Upright', font: GoogleFonts.cormorantUpright()),
  BaoFontList(label: 'Courgette', font: GoogleFonts.courgette()),
  BaoFontList(label: 'Courier Prime', font: GoogleFonts.courierPrime()),
  BaoFontList(label: 'Cousine', font: GoogleFonts.cousine()),
  BaoFontList(label: 'Coustard', font: GoogleFonts.coustard()),
  BaoFontList(label: 'Covered By Your Grace', font: GoogleFonts.coveredByYourGrace()),
  BaoFontList(label: 'Crafty Girls', font: GoogleFonts.craftyGirls()),
  BaoFontList(label: 'Creepster', font: GoogleFonts.creepster()),
  BaoFontList(label: 'Crete Round', font: GoogleFonts.creteRound()),
  BaoFontList(label: 'Crimson Pro', font: GoogleFonts.crimsonPro()),
  BaoFontList(label: 'Crimson Text', font: GoogleFonts.crimsonText()),
  BaoFontList(label: 'Croissant One', font: GoogleFonts.croissantOne()),
  BaoFontList(label: 'Crushed', font: GoogleFonts.crushed()),
  BaoFontList(label: 'Cuprum', font: GoogleFonts.cuprum()),
  BaoFontList(label: 'Cute Font', font: GoogleFonts.cuteFont()),
  BaoFontList(label: 'Cutive', font: GoogleFonts.cutive()),
  BaoFontList(label: 'Cutive Mono', font: GoogleFonts.cutiveMono()),
  BaoFontList(label: 'DM Mono', font: GoogleFonts.dmMono()),
  BaoFontList(label: 'DM Sans', font: GoogleFonts.dmSans()),
  BaoFontList(label: 'DM Serif Display', font: GoogleFonts.dmSerifDisplay()),
  BaoFontList(label: 'DM Serif Text', font: GoogleFonts.dmSerifText()),
  BaoFontList(label: 'Damion', font: GoogleFonts.damion()),
  BaoFontList(label: 'Dancing Script', font: GoogleFonts.dancingScript()),
  BaoFontList(label: 'Darker Grotesque', font: GoogleFonts.darkerGrotesque()),
  BaoFontList(label: 'David Libre', font: GoogleFonts.davidLibre()),
  BaoFontList(label: 'Dawning of a New Day', font: GoogleFonts.dawningOfANewDay()),
  BaoFontList(label: 'Days One', font: GoogleFonts.daysOne()),
  BaoFontList(label: 'Dekko', font: GoogleFonts.dekko()),
  BaoFontList(label: 'Dela Gothic One', font: GoogleFonts.delaGothicOne()),
  BaoFontList(label: 'Delius', font: GoogleFonts.delius()),
  BaoFontList(label: 'Delius Swash Caps', font: GoogleFonts.deliusSwashCaps()),
  BaoFontList(label: 'Delius Unicase', font: GoogleFonts.deliusUnicase()),
  BaoFontList(label: 'Della Respira', font: GoogleFonts.dellaRespira()),
  BaoFontList(label: 'Denk One', font: GoogleFonts.denkOne()),
  BaoFontList(label: 'Devonshire', font: GoogleFonts.devonshire()),
  BaoFontList(label: 'Dhurjati', font: GoogleFonts.dhurjati()),
  BaoFontList(label: 'Didact Gothic', font: GoogleFonts.didactGothic()),
  BaoFontList(label: 'Diplomata', font: GoogleFonts.diplomata()),
  BaoFontList(label: 'Diplomata SC', font: GoogleFonts.diplomataSc()),
  BaoFontList(label: 'Do Hyeon', font: GoogleFonts.doHyeon()),
  BaoFontList(label: 'Dokdo', font: GoogleFonts.dokdo()),
  BaoFontList(label: 'Domine', font: GoogleFonts.domine()),
  BaoFontList(label: 'Donegal One', font: GoogleFonts.donegalOne()),
  BaoFontList(label: 'Dongle', font: GoogleFonts.dongle()),
  BaoFontList(label: 'Doppio One', font: GoogleFonts.doppioOne()),
  BaoFontList(label: 'Dorsa', font: GoogleFonts.dorsa()),
  BaoFontList(label: 'Dosis', font: GoogleFonts.dosis()),
  BaoFontList(label: 'DotGothic16', font: GoogleFonts.dotGothic16()),
  BaoFontList(label: 'Dr Sugiyama', font: GoogleFonts.drSugiyama()),
  BaoFontList(label: 'Droid Sans', font: GoogleFonts.droidSans()),
  BaoFontList(label: 'Droid Sans Mono', font: GoogleFonts.droidSansMono()),
  BaoFontList(label: 'Droid Serif', font: GoogleFonts.droidSerif()),
  BaoFontList(label: 'Duru Sans', font: GoogleFonts.duruSans()),
  BaoFontList(label: 'Dynalight', font: GoogleFonts.dynalight()),
  BaoFontList(label: 'EB Garamond', font: GoogleFonts.ebGaramond()),
  BaoFontList(label: 'Eagle Lake', font: GoogleFonts.eagleLake()),
  BaoFontList(label: 'East Sea Dokdo', font: GoogleFonts.eastSeaDokdo()),
  BaoFontList(label: 'Eater', font: GoogleFonts.eater()),
  BaoFontList(label: 'Economica', font: GoogleFonts.economica()),
  BaoFontList(label: 'Eczar', font: GoogleFonts.eczar()),
  BaoFontList(label: 'El Messiri', font: GoogleFonts.elMessiri()),
  BaoFontList(label: 'Electrolize', font: GoogleFonts.electrolize()),
  BaoFontList(label: 'Elsie', font: GoogleFonts.elsie()),
  BaoFontList(label: 'Elsie Swash Caps', font: GoogleFonts.elsieSwashCaps()),
  BaoFontList(label: 'Emblema One', font: GoogleFonts.emblemaOne()),
  BaoFontList(label: 'Emilys Candy', font: GoogleFonts.emilysCandy()),
  BaoFontList(label: 'Encode Sans', font: GoogleFonts.encodeSans()),
  BaoFontList(label: 'Encode Sans Condensed', font: GoogleFonts.encodeSansCondensed()),
  BaoFontList(label: 'Encode Sans Expanded', font: GoogleFonts.encodeSansExpanded()),
  BaoFontList(label: 'Encode Sans SC', font: GoogleFonts.encodeSansSc()),
  BaoFontList(label: 'Encode Sans Semi Condensed', font: GoogleFonts.encodeSansSemiCondensed()),
  BaoFontList(label: 'Encode Sans Semi Expanded', font: GoogleFonts.encodeSansSemiExpanded()),
  BaoFontList(label: 'Engagement', font: GoogleFonts.engagement()),
  BaoFontList(label: 'Englebert', font: GoogleFonts.englebert()),
  BaoFontList(label: 'Enriqueta', font: GoogleFonts.enriqueta()),
  BaoFontList(label: 'Ephesis', font: GoogleFonts.ephesis()),
  BaoFontList(label: 'Epilogue', font: GoogleFonts.epilogue()),
  BaoFontList(label: 'Erica One', font: GoogleFonts.ericaOne()),
  BaoFontList(label: 'Esteban', font: GoogleFonts.esteban()),
  BaoFontList(label: 'Estonia', font: GoogleFonts.estonia()),
  BaoFontList(label: 'Euphoria Script', font: GoogleFonts.euphoriaScript()),
  BaoFontList(label: 'Ewert', font: GoogleFonts.ewert()),
  BaoFontList(label: 'Exo', font: GoogleFonts.exo()),
  BaoFontList(label: 'Exo 2', font: GoogleFonts.exo2()),
  BaoFontList(label: 'Expletus Sans', font: GoogleFonts.expletusSans()),
  BaoFontList(label: 'Explora', font: GoogleFonts.explora()),
  BaoFontList(label: 'Fahkwang', font: GoogleFonts.fahkwang()),
  BaoFontList(label: 'Fanwood Text', font: GoogleFonts.fanwoodText()),
  BaoFontList(label: 'Farro', font: GoogleFonts.farro()),
  BaoFontList(label: 'Farsan', font: GoogleFonts.farsan()),
  BaoFontList(label: 'Fascinate', font: GoogleFonts.fascinate()),
  BaoFontList(label: 'Fascinate Inline', font: GoogleFonts.fascinateInline()),
  BaoFontList(label: 'Faster One', font: GoogleFonts.fasterOne()),
  BaoFontList(label: 'Fauna One', font: GoogleFonts.faunaOne()),
  BaoFontList(label: 'Faustina', font: GoogleFonts.faustina()),
  BaoFontList(label: 'Federant', font: GoogleFonts.federant()),
  BaoFontList(label: 'Federo', font: GoogleFonts.federo()),
  BaoFontList(label: 'Felipa', font: GoogleFonts.felipa()),
  BaoFontList(label: 'Fenix', font: GoogleFonts.fenix()),
  BaoFontList(label: 'Festive', font: GoogleFonts.festive()),
  BaoFontList(label: 'Finger Paint', font: GoogleFonts.fingerPaint()),
  BaoFontList(label: 'Fira Code', font: GoogleFonts.firaCode()),
  BaoFontList(label: 'Fira Mono', font: GoogleFonts.firaMono()),
  BaoFontList(label: 'Fira Sans', font: GoogleFonts.firaSans()),
  BaoFontList(label: 'Fira Sans Condensed', font: GoogleFonts.firaSansCondensed()),
  BaoFontList(label: 'Fira Sans Extra Condensed', font: GoogleFonts.firaSansExtraCondensed()),
  BaoFontList(label: 'Fjalla One', font: GoogleFonts.fjallaOne()),
  BaoFontList(label: 'Fjord One', font: GoogleFonts.fjordOne()),
  BaoFontList(label: 'Flamenco', font: GoogleFonts.flamenco()),
  BaoFontList(label: 'Flavors', font: GoogleFonts.flavors()),
  BaoFontList(label: 'Fleur De Leah', font: GoogleFonts.fleurDeLeah()),
  BaoFontList(label: 'Flow Block', font: GoogleFonts.flowBlock()),
  BaoFontList(label: 'Flow Circular', font: GoogleFonts.flowCircular()),
  BaoFontList(label: 'Flow Rounded', font: GoogleFonts.flowRounded()),
  BaoFontList(label: 'Fondamento', font: GoogleFonts.fondamento()),
  BaoFontList(label: 'Fontdiner Swanky', font: GoogleFonts.fontdinerSwanky()),
  BaoFontList(label: 'Forum', font: GoogleFonts.forum()),
  BaoFontList(label: 'Francois One', font: GoogleFonts.francoisOne()),
  BaoFontList(label: 'Frank Ruhl Libre', font: GoogleFonts.frankRuhlLibre()),
  BaoFontList(label: 'Fraunces', font: GoogleFonts.fraunces()),
  BaoFontList(label: 'Freckle Face', font: GoogleFonts.freckleFace()),
  BaoFontList(label: 'Fredericka the Great', font: GoogleFonts.frederickaTheGreat()),
  BaoFontList(label: 'Fredoka One', font: GoogleFonts.fredokaOne()),
  BaoFontList(label: 'Fresca', font: GoogleFonts.fresca()),
  BaoFontList(label: 'Frijole', font: GoogleFonts.frijole()),
  BaoFontList(label: 'Fruktur', font: GoogleFonts.fruktur()),
  BaoFontList(label: 'Fugaz One', font: GoogleFonts.fugazOne()),
  BaoFontList(label: 'Fuggles', font: GoogleFonts.fuggles()),
  BaoFontList(label: 'Fuzzy Bubbles', font: GoogleFonts.fuzzyBubbles()),
  BaoFontList(label: 'GFS Didot', font: GoogleFonts.gfsDidot()),
  BaoFontList(label: 'GFS Neohellenic', font: GoogleFonts.gfsNeohellenic()),
  BaoFontList(label: 'Gabriela', font: GoogleFonts.gabriela()),
  BaoFontList(label: 'Gaegu', font: GoogleFonts.gaegu()),
  BaoFontList(label: 'Gafata', font: GoogleFonts.gafata()),
  BaoFontList(label: 'Galada', font: GoogleFonts.galada()),
  BaoFontList(label: 'Galdeano', font: GoogleFonts.galdeano()),
  BaoFontList(label: 'Galindo', font: GoogleFonts.galindo()),
  BaoFontList(label: 'Gamja Flower', font: GoogleFonts.gamjaFlower()),
  BaoFontList(label: 'Gayathri', font: GoogleFonts.gayathri()),
  BaoFontList(label: 'Gelasio', font: GoogleFonts.gelasio()),
  BaoFontList(label: 'Gemunu Libre', font: GoogleFonts.gemunuLibre()),
  BaoFontList(label: 'Genos', font: GoogleFonts.genos()),
  BaoFontList(label: 'Gentium Basic', font: GoogleFonts.gentiumBasic()),
  BaoFontList(label: 'Gentium Book Basic', font: GoogleFonts.gentiumBookBasic()),
  BaoFontList(label: 'Geo', font: GoogleFonts.geo()),
  BaoFontList(label: 'Georama', font: GoogleFonts.georama()),
  BaoFontList(label: 'Geostar', font: GoogleFonts.geostar()),
  BaoFontList(label: 'Geostar Fill', font: GoogleFonts.geostarFill()),
  BaoFontList(label: 'Germania One', font: GoogleFonts.germaniaOne()),
  BaoFontList(label: 'Gideon Roman', font: GoogleFonts.gideonRoman()),
  BaoFontList(label: 'Gidugu', font: GoogleFonts.gidugu()),
  BaoFontList(label: 'Gilda Display', font: GoogleFonts.gildaDisplay()),
  BaoFontList(label: 'Girassol', font: GoogleFonts.girassol()),
  BaoFontList(label: 'Give You Glory', font: GoogleFonts.giveYouGlory()),
  BaoFontList(label: 'Glass Antiqua', font: GoogleFonts.glassAntiqua()),
  BaoFontList(label: 'Glegoo', font: GoogleFonts.glegoo()),
  BaoFontList(label: 'Gloria Hallelujah', font: GoogleFonts.gloriaHallelujah()),
  BaoFontList(label: 'Glory', font: GoogleFonts.glory()),
  BaoFontList(label: 'Gluten', font: GoogleFonts.gluten()),
  BaoFontList(label: 'Goblin One', font: GoogleFonts.goblinOne()),
  BaoFontList(label: 'Gochi Hand', font: GoogleFonts.gochiHand()),
  BaoFontList(label: 'Goldman', font: GoogleFonts.goldman()),
  BaoFontList(label: 'Gorditas', font: GoogleFonts.gorditas()),
  BaoFontList(label: 'Gothic A1', font: GoogleFonts.gothicA1()),
  BaoFontList(label: 'Gotu', font: GoogleFonts.gotu()),
  BaoFontList(label: 'Goudy Bookletter 1911', font: GoogleFonts.goudyBookletter1911()),
  BaoFontList(label: 'Gowun Batang', font: GoogleFonts.gowunBatang()),
  BaoFontList(label: 'Gowun Dodum', font: GoogleFonts.gowunDodum()),
  BaoFontList(label: 'Graduate', font: GoogleFonts.graduate()),
  BaoFontList(label: 'Grand Hotel', font: GoogleFonts.grandHotel()),
  BaoFontList(label: 'Grandstander', font: GoogleFonts.grandstander()),
  BaoFontList(label: 'Gravitas One', font: GoogleFonts.gravitasOne()),
  BaoFontList(label: 'Great Vibes', font: GoogleFonts.greatVibes()),
  BaoFontList(label: 'Grechen Fuemen', font: GoogleFonts.grechenFuemen()),
  BaoFontList(label: 'Grenze', font: GoogleFonts.grenze()),
  BaoFontList(label: 'Grenze Gotisch', font: GoogleFonts.grenzeGotisch()),
  BaoFontList(label: 'Grey Qo', font: GoogleFonts.greyQo()),
  BaoFontList(label: 'Griffy', font: GoogleFonts.griffy()),
  BaoFontList(label: 'Gruppo', font: GoogleFonts.gruppo()),
  BaoFontList(label: 'Gudea', font: GoogleFonts.gudea()),
  BaoFontList(label: 'Gugi', font: GoogleFonts.gugi()),
  BaoFontList(label: 'Gupter', font: GoogleFonts.gupter()),
  BaoFontList(label: 'Gurajada', font: GoogleFonts.gurajada()),
  BaoFontList(label: 'Gwendolyn', font: GoogleFonts.gwendolyn()),
  BaoFontList(label: 'Habibi', font: GoogleFonts.habibi()),
  BaoFontList(label: 'Hachi Maru Pop', font: GoogleFonts.hachiMaruPop()),
  BaoFontList(label: 'Hahmlet', font: GoogleFonts.hahmlet()),
  BaoFontList(label: 'Halant', font: GoogleFonts.halant()),
  BaoFontList(label: 'Hammersmith One', font: GoogleFonts.hammersmithOne()),
  BaoFontList(label: 'Hanalei', font: GoogleFonts.hanalei()),
  BaoFontList(label: 'Hanalei Fill', font: GoogleFonts.hanaleiFill()),
  BaoFontList(label: 'Handlee', font: GoogleFonts.handlee()),
  BaoFontList(label: 'Happy Monkey', font: GoogleFonts.happyMonkey()),
  BaoFontList(label: 'Harmattan', font: GoogleFonts.harmattan()),
  BaoFontList(label: 'Headland One', font: GoogleFonts.headlandOne()),
  BaoFontList(label: 'Heebo', font: GoogleFonts.heebo()),
  BaoFontList(label: 'Henny Penny', font: GoogleFonts.hennyPenny()),
  BaoFontList(label: 'Hepta Slab', font: GoogleFonts.heptaSlab()),
  BaoFontList(label: 'Herr Von Muellerhoff', font: GoogleFonts.herrVonMuellerhoff()),
  BaoFontList(label: 'Hi Melody', font: GoogleFonts.hiMelody()),
  BaoFontList(label: 'Hina Mincho', font: GoogleFonts.hinaMincho()),
  BaoFontList(label: 'Hind', font: GoogleFonts.hind()),
  BaoFontList(label: 'Hind Guntur', font: GoogleFonts.hindGuntur()),
  BaoFontList(label: 'Hind Madurai', font: GoogleFonts.hindMadurai()),
  BaoFontList(label: 'Hind Siliguri', font: GoogleFonts.hindSiliguri()),
  BaoFontList(label: 'Hind Vadodara', font: GoogleFonts.hindVadodara()),
  BaoFontList(label: 'Holtwood One SC', font: GoogleFonts.holtwoodOneSc()),
  BaoFontList(label: 'Homemade Apple', font: GoogleFonts.homemadeApple()),
  BaoFontList(label: 'Homenaje', font: GoogleFonts.homenaje()),
  BaoFontList(label: 'Hurricane', font: GoogleFonts.hurricane()),
  BaoFontList(label: 'IBM Plex Mono', font: GoogleFonts.ibmPlexMono()),
  BaoFontList(label: 'IBM Plex Sans', font: GoogleFonts.ibmPlexSans()),
  BaoFontList(label: 'IBM Plex Sans Arabic', font: GoogleFonts.ibmPlexSansArabic()),
  BaoFontList(label: 'IBM Plex Sans Condensed', font: GoogleFonts.ibmPlexSansCondensed()),
  BaoFontList(label: 'IBM Plex Sans Devanagari', font: GoogleFonts.ibmPlexSansDevanagari()),
  BaoFontList(label: 'IBM Plex Sans Hebrew', font: GoogleFonts.ibmPlexSansHebrew()),
  BaoFontList(label: 'IBM Plex Sans KR', font: GoogleFonts.ibmPlexSansKr()),
  BaoFontList(label: 'IBM Plex Sans Thai', font: GoogleFonts.ibmPlexSansThai()),
  BaoFontList(label: 'IBM Plex Sans Thai Looped', font: GoogleFonts.ibmPlexSansThaiLooped()),
  BaoFontList(label: 'IBM Plex Serif', font: GoogleFonts.ibmPlexSerif()),
  BaoFontList(label: 'IM Fell DW Pica', font: GoogleFonts.imFellDwPica()),
  BaoFontList(label: 'IM Fell DW Pica SC', font: GoogleFonts.imFellDwPicaSc()),
  BaoFontList(label: 'IM Fell Double Pica', font: GoogleFonts.imFellDoublePica()),
  BaoFontList(label: 'IM Fell Double Pica SC', font: GoogleFonts.imFellDoublePicaSc()),
  BaoFontList(label: 'IM Fell English', font: GoogleFonts.imFellEnglish()),
  BaoFontList(label: 'IM Fell English SC', font: GoogleFonts.imFellEnglishSc()),
  BaoFontList(label: 'IM Fell French Canon', font: GoogleFonts.imFellFrenchCanon()),
  BaoFontList(label: 'IM Fell French Canon SC', font: GoogleFonts.imFellFrenchCanonSc()),
  BaoFontList(label: 'IM Fell Great Primer', font: GoogleFonts.imFellGreatPrimer()),
  BaoFontList(label: 'IM Fell Great Primer SC', font: GoogleFonts.imFellGreatPrimerSc()),
  BaoFontList(label: 'Ibarra Real Nova', font: GoogleFonts.ibarraRealNova()),
  BaoFontList(label: 'Iceberg', font: GoogleFonts.iceberg()),
  BaoFontList(label: 'Iceland', font: GoogleFonts.iceland()),
  BaoFontList(label: 'Imprima', font: GoogleFonts.imprima()),
  BaoFontList(label: 'Inconsolata', font: GoogleFonts.inconsolata()),
  BaoFontList(label: 'Inder', font: GoogleFonts.inder()),
  BaoFontList(label: 'Indie Flower', font: GoogleFonts.indieFlower()),
  BaoFontList(label: 'Inika', font: GoogleFonts.inika()),
  BaoFontList(label: 'Inknut Antiqua', font: GoogleFonts.inknutAntiqua()),
  BaoFontList(label: 'Inria Sans', font: GoogleFonts.inriaSans()),
  BaoFontList(label: 'Inria Serif', font: GoogleFonts.inriaSerif()),
  BaoFontList(label: 'Inter', font: GoogleFonts.inter()),
  BaoFontList(label: 'Irish Grover', font: GoogleFonts.irishGrover()),
  BaoFontList(label: 'Istok Web', font: GoogleFonts.istokWeb()),
  BaoFontList(label: 'Italiana', font: GoogleFonts.italiana()),
  BaoFontList(label: 'Italianno', font: GoogleFonts.italianno()),
  BaoFontList(label: 'Itim', font: GoogleFonts.itim()),
  BaoFontList(label: 'Jacques Francois', font: GoogleFonts.jacquesFrancois()),
  BaoFontList(label: 'Jacques Francois Shadow', font: GoogleFonts.jacquesFrancoisShadow()),
  BaoFontList(label: 'Jaldi', font: GoogleFonts.jaldi()),
  BaoFontList(label: 'JetBrains Mono', font: GoogleFonts.jetBrainsMono()),
  BaoFontList(label: 'Jim Nightshade', font: GoogleFonts.jimNightshade()),
  BaoFontList(label: 'Jockey One', font: GoogleFonts.jockeyOne()),
  BaoFontList(label: 'Jolly Lodger', font: GoogleFonts.jollyLodger()),
  BaoFontList(label: 'Jomhuria', font: GoogleFonts.jomhuria()),
  BaoFontList(label: 'Jomolhari', font: GoogleFonts.jomolhari()),
  BaoFontList(label: 'Josefin Sans', font: GoogleFonts.josefinSans()),
  BaoFontList(label: 'Josefin Slab', font: GoogleFonts.josefinSlab()),
  BaoFontList(label: 'Jost', font: GoogleFonts.jost()),
  BaoFontList(label: 'Joti One', font: GoogleFonts.jotiOne()),
  BaoFontList(label: 'Jua', font: GoogleFonts.jua()),
  BaoFontList(label: 'Judson', font: GoogleFonts.judson()),
  BaoFontList(label: 'Julee', font: GoogleFonts.julee()),
  BaoFontList(label: 'Julius Sans One', font: GoogleFonts.juliusSansOne()),
  BaoFontList(label: 'Junge', font: GoogleFonts.junge()),
  BaoFontList(label: 'Jura', font: GoogleFonts.jura()),
  BaoFontList(label: 'Just Another Hand', font: GoogleFonts.justAnotherHand()),
  BaoFontList(label: 'Just Me Again Down Here', font: GoogleFonts.justMeAgainDownHere()),
  BaoFontList(label: 'K2D', font: GoogleFonts.k2d()),
  BaoFontList(label: 'Kadwa', font: GoogleFonts.kadwa()),
  BaoFontList(label: 'Kaisei Decol', font: GoogleFonts.kaiseiDecol()),
  BaoFontList(label: 'Kaisei HarunoUmi', font: GoogleFonts.kaiseiHarunoUmi()),
  BaoFontList(label: 'Kaisei Opti', font: GoogleFonts.kaiseiOpti()),
  BaoFontList(label: 'Kaisei Tokumin', font: GoogleFonts.kaiseiTokumin()),
  BaoFontList(label: 'Kalam', font: GoogleFonts.kalam()),
  BaoFontList(label: 'Kameron', font: GoogleFonts.kameron()),
  BaoFontList(label: 'Kanit', font: GoogleFonts.kanit()),
  BaoFontList(label: 'Kantumruy', font: GoogleFonts.kantumruy()),
  BaoFontList(label: 'Karla', font: GoogleFonts.karla()),
  BaoFontList(label: 'Karma', font: GoogleFonts.karma()),
  BaoFontList(label: 'Katibeh', font: GoogleFonts.katibeh()),
  BaoFontList(label: 'Kaushan Script', font: GoogleFonts.kaushanScript()),
  BaoFontList(label: 'Kavivanar', font: GoogleFonts.kavivanar()),
  BaoFontList(label: 'Kavoon', font: GoogleFonts.kavoon()),
  BaoFontList(label: 'Kdam Thmor', font: GoogleFonts.kdamThmor()),
  BaoFontList(label: 'Keania One', font: GoogleFonts.keaniaOne()),
  BaoFontList(label: 'Kelly Slab', font: GoogleFonts.kellySlab()),
  BaoFontList(label: 'Kenia', font: GoogleFonts.kenia()),
  BaoFontList(label: 'Khand', font: GoogleFonts.khand()),
  BaoFontList(label: 'Khula', font: GoogleFonts.khula()),
  BaoFontList(label: 'Kings', font: GoogleFonts.kings()),
  BaoFontList(label: 'Kirang Haerang', font: GoogleFonts.kirangHaerang()),
  BaoFontList(label: 'Kite One', font: GoogleFonts.kiteOne()),
  BaoFontList(label: 'Klee One', font: GoogleFonts.kleeOne()),
  BaoFontList(label: 'Knewave', font: GoogleFonts.knewave()),
  BaoFontList(label: 'KoHo', font: GoogleFonts.koHo()),
  BaoFontList(label: 'Kodchasan', font: GoogleFonts.kodchasan()),
  BaoFontList(label: 'Koh Santepheap', font: GoogleFonts.kohSantepheap()),
  BaoFontList(label: 'Kosugi', font: GoogleFonts.kosugi()),
  BaoFontList(label: 'Kosugi Maru', font: GoogleFonts.kosugiMaru()),
  BaoFontList(label: 'Kotta One', font: GoogleFonts.kottaOne()),
  BaoFontList(label: 'Kranky', font: GoogleFonts.kranky()),
  BaoFontList(label: 'Kreon', font: GoogleFonts.kreon()),
  BaoFontList(label: 'Kristi', font: GoogleFonts.kristi()),
  BaoFontList(label: 'Krona One', font: GoogleFonts.kronaOne()),
  BaoFontList(label: 'Krub', font: GoogleFonts.krub()),
  BaoFontList(label: 'Kufam', font: GoogleFonts.kufam()),
  BaoFontList(label: 'Kulim Park', font: GoogleFonts.kulimPark()),
  BaoFontList(label: 'Kumar One', font: GoogleFonts.kumarOne()),
  BaoFontList(label: 'Kumar One Outline', font: GoogleFonts.kumarOneOutline()),
  BaoFontList(label: 'Kumbh Sans', font: GoogleFonts.kumbhSans()),
  BaoFontList(label: 'Kurale', font: GoogleFonts.kurale()),
  BaoFontList(label: 'La Belle Aurore', font: GoogleFonts.laBelleAurore()),
  BaoFontList(label: 'Lacquer', font: GoogleFonts.lacquer()),
  BaoFontList(label: 'Laila', font: GoogleFonts.laila()),
  BaoFontList(label: 'Lakki Reddy', font: GoogleFonts.lakkiReddy()),
  BaoFontList(label: 'Lalezar', font: GoogleFonts.lalezar()),
  BaoFontList(label: 'Lancelot', font: GoogleFonts.lancelot()),
  BaoFontList(label: 'Langar', font: GoogleFonts.langar()),
  BaoFontList(label: 'Lateef', font: GoogleFonts.lateef()),
  BaoFontList(label: 'Lato', font: GoogleFonts.lato()),
  BaoFontList(label: 'League Script', font: GoogleFonts.leagueScript()),
  BaoFontList(label: 'Leckerli One', font: GoogleFonts.leckerliOne()),
  BaoFontList(label: 'Ledger', font: GoogleFonts.ledger()),
  BaoFontList(label: 'Lekton', font: GoogleFonts.lekton()),
  BaoFontList(label: 'Lemon', font: GoogleFonts.lemon()),
  BaoFontList(label: 'Lemonada', font: GoogleFonts.lemonada()),
  BaoFontList(label: 'Lexend', font: GoogleFonts.lexend()),
  BaoFontList(label: 'Lexend Deca', font: GoogleFonts.lexendDeca()),
  BaoFontList(label: 'Lexend Exa', font: GoogleFonts.lexendExa()),
  BaoFontList(label: 'Lexend Giga', font: GoogleFonts.lexendGiga()),
  BaoFontList(label: 'Lexend Mega', font: GoogleFonts.lexendMega()),
  BaoFontList(label: 'Lexend Peta', font: GoogleFonts.lexendPeta()),
  BaoFontList(label: 'Lexend Tera', font: GoogleFonts.lexendTera()),
  BaoFontList(label: 'Lexend Zetta', font: GoogleFonts.lexendZetta()),
  BaoFontList(label: 'Libre Barcode 128', font: GoogleFonts.libreBarcode128()),
  BaoFontList(label: 'Libre Barcode 128 Text', font: GoogleFonts.libreBarcode128Text()),
  BaoFontList(label: 'Libre Barcode 39', font: GoogleFonts.libreBarcode39()),
  BaoFontList(label: 'Libre Barcode 39 Extended', font: GoogleFonts.libreBarcode39Extended()),
  BaoFontList(label: 'Libre Barcode 39 Extended Text', font: GoogleFonts.libreBarcode39ExtendedText()),
  BaoFontList(label: 'Libre Barcode 39 Text', font: GoogleFonts.libreBarcode39Text()),
  BaoFontList(label: 'Libre Baskerville', font: GoogleFonts.libreBaskerville()),
  BaoFontList(label: 'Libre Caslon Display', font: GoogleFonts.libreCaslonDisplay()),
  BaoFontList(label: 'Libre Caslon Text', font: GoogleFonts.libreCaslonText()),
  BaoFontList(label: 'Libre Franklin', font: GoogleFonts.libreFranklin()),
  BaoFontList(label: 'Life Savers', font: GoogleFonts.lifeSavers()),
  BaoFontList(label: 'Lilita One', font: GoogleFonts.lilitaOne()),
  BaoFontList(label: 'Lily Script One', font: GoogleFonts.lilyScriptOne()),
  BaoFontList(label: 'Limelight', font: GoogleFonts.limelight()),
  BaoFontList(label: 'Linden Hill', font: GoogleFonts.lindenHill()),
  BaoFontList(label: 'Literata', font: GoogleFonts.literata()),
  BaoFontList(label: 'Liu Jian Mao Cao', font: GoogleFonts.liuJianMaoCao()),
  BaoFontList(label: 'Livvic', font: GoogleFonts.livvic()),
  BaoFontList(label: 'Lobster', font: GoogleFonts.lobster()),
  BaoFontList(label: 'Lobster Two', font: GoogleFonts.lobsterTwo()),
  BaoFontList(label: 'Londrina Outline', font: GoogleFonts.londrinaOutline()),
  BaoFontList(label: 'Londrina Shadow', font: GoogleFonts.londrinaShadow()),
  BaoFontList(label: 'Londrina Sketch', font: GoogleFonts.londrinaSketch()),
  BaoFontList(label: 'Londrina Solid', font: GoogleFonts.londrinaSolid()),
  BaoFontList(label: 'Long Cang', font: GoogleFonts.longCang()),
  BaoFontList(label: 'Lora', font: GoogleFonts.lora()),
  BaoFontList(label: 'Love Ya Like A Sister', font: GoogleFonts.loveYaLikeASister()),
  BaoFontList(label: 'Loved by the King', font: GoogleFonts.lovedByTheKing()),
  BaoFontList(label: 'Lovers Quarrel', font: GoogleFonts.loversQuarrel()),
  BaoFontList(label: 'Luckiest Guy', font: GoogleFonts.luckiestGuy()),
  BaoFontList(label: 'Lusitana', font: GoogleFonts.lusitana()),
  BaoFontList(label: 'Lustria', font: GoogleFonts.lustria()),
  BaoFontList(label: 'Luxurious Script', font: GoogleFonts.luxuriousScript()),
  BaoFontList(label: 'M PLUS 1', font: GoogleFonts.mPlus1()),
  BaoFontList(label: 'M PLUS 1 Code', font: GoogleFonts.mPlus1Code()),
  BaoFontList(label: 'M PLUS 1p', font: GoogleFonts.mPlus1p()),
  BaoFontList(label: 'M PLUS 2', font: GoogleFonts.mPlus2()),
  BaoFontList(label: 'M PLUS Code Latin', font: GoogleFonts.mPlusCodeLatin()),
  BaoFontList(label: 'M PLUS Rounded 1c', font: GoogleFonts.mPlusRounded1c()),
  BaoFontList(label: 'Ma Shan Zheng', font: GoogleFonts.maShanZheng()),
  BaoFontList(label: 'Macondo', font: GoogleFonts.macondo()),
  BaoFontList(label: 'Macondo Swash Caps', font: GoogleFonts.macondoSwashCaps()),
  BaoFontList(label: 'Mada', font: GoogleFonts.mada()),
  BaoFontList(label: 'Magra', font: GoogleFonts.magra()),
  BaoFontList(label: 'Maiden Orange', font: GoogleFonts.maidenOrange()),
  BaoFontList(label: 'Maitree', font: GoogleFonts.maitree()),
  BaoFontList(label: 'Major Mono Display', font: GoogleFonts.majorMonoDisplay()),
  BaoFontList(label: 'Mako', font: GoogleFonts.mako()),
  BaoFontList(label: 'Mali', font: GoogleFonts.mali()),
  BaoFontList(label: 'Mallanna', font: GoogleFonts.mallanna()),
  BaoFontList(label: 'Mandali', font: GoogleFonts.mandali()),
  BaoFontList(label: 'Manjari', font: GoogleFonts.manjari()),
  BaoFontList(label: 'Manrope', font: GoogleFonts.manrope()),
  BaoFontList(label: 'Mansalva', font: GoogleFonts.mansalva()),
  BaoFontList(label: 'Manuale', font: GoogleFonts.manuale()),
  BaoFontList(label: 'Marcellus', font: GoogleFonts.marcellus()),
  BaoFontList(label: 'Marcellus SC', font: GoogleFonts.marcellusSc()),
  BaoFontList(label: 'Marck Script', font: GoogleFonts.marckScript()),
  BaoFontList(label: 'Margarine', font: GoogleFonts.margarine()),
  BaoFontList(label: 'Markazi Text', font: GoogleFonts.markaziText()),
  BaoFontList(label: 'Marko One', font: GoogleFonts.markoOne()),
  BaoFontList(label: 'Marmelad', font: GoogleFonts.marmelad()),
  BaoFontList(label: 'Martel', font: GoogleFonts.martel()),
  BaoFontList(label: 'Martel Sans', font: GoogleFonts.martelSans()),
  BaoFontList(label: 'Marvel', font: GoogleFonts.marvel()),
  BaoFontList(label: 'Mate', font: GoogleFonts.mate()),
  BaoFontList(label: 'Mate SC', font: GoogleFonts.mateSc()),
  BaoFontList(label: 'Maven Pro', font: GoogleFonts.mavenPro()),
  BaoFontList(label: 'McLaren', font: GoogleFonts.mcLaren()),
  BaoFontList(label: 'Meddon', font: GoogleFonts.meddon()),
  BaoFontList(label: 'MedievalSharp', font: GoogleFonts.medievalSharp()),
  BaoFontList(label: 'Medula One', font: GoogleFonts.medulaOne()),
  BaoFontList(label: 'Meera Inimai', font: GoogleFonts.meeraInimai()),
  BaoFontList(label: 'Megrim', font: GoogleFonts.megrim()),
  BaoFontList(label: 'Meie Script', font: GoogleFonts.meieScript()),
  BaoFontList(label: 'Meow Script', font: GoogleFonts.meowScript()),
  BaoFontList(label: 'Merienda', font: GoogleFonts.merienda()),
  BaoFontList(label: 'Merienda One', font: GoogleFonts.meriendaOne()),
  BaoFontList(label: 'Merriweather', font: GoogleFonts.merriweather()),
  BaoFontList(label: 'Merriweather Sans', font: GoogleFonts.merriweatherSans()),
  BaoFontList(label: 'Metal Mania', font: GoogleFonts.metalMania()),
  BaoFontList(label: 'Metamorphous', font: GoogleFonts.metamorphous()),
  BaoFontList(label: 'Metrophobic', font: GoogleFonts.metrophobic()),
  BaoFontList(label: 'Michroma', font: GoogleFonts.michroma()),
  BaoFontList(label: 'Milonga', font: GoogleFonts.milonga()),
  BaoFontList(label: 'Miltonian', font: GoogleFonts.miltonian()),
  BaoFontList(label: 'Miltonian Tattoo', font: GoogleFonts.miltonianTattoo()),
  BaoFontList(label: 'Mina', font: GoogleFonts.mina()),
  BaoFontList(label: 'Miniver', font: GoogleFonts.miniver()),
  BaoFontList(label: 'Miriam Libre', font: GoogleFonts.miriamLibre()),
  BaoFontList(label: 'Mirza', font: GoogleFonts.mirza()),
  BaoFontList(label: 'Miss Fajardose', font: GoogleFonts.missFajardose()),
  BaoFontList(label: 'Mitr', font: GoogleFonts.mitr()),
  BaoFontList(label: 'Mochiy Pop One', font: GoogleFonts.mochiyPopOne()),
  BaoFontList(label: 'Mochiy Pop P One', font: GoogleFonts.mochiyPopPOne()),
  BaoFontList(label: 'Modak', font: GoogleFonts.modak()),
  BaoFontList(label: 'Modern Antiqua', font: GoogleFonts.modernAntiqua()),
  BaoFontList(label: 'Mogra', font: GoogleFonts.mogra()),
  BaoFontList(label: 'Mohave', font: GoogleFonts.mohave()),
  BaoFontList(label: 'Molengo', font: GoogleFonts.molengo()),
  BaoFontList(label: 'Molle', font: GoogleFonts.molle()),
  BaoFontList(label: 'Monda', font: GoogleFonts.monda()),
  BaoFontList(label: 'Monofett', font: GoogleFonts.monofett()),
  BaoFontList(label: 'Monoton', font: GoogleFonts.monoton()),
  BaoFontList(label: 'Monsieur La Doulaise', font: GoogleFonts.monsieurLaDoulaise()),
  BaoFontList(label: 'Montaga', font: GoogleFonts.montaga()),
  BaoFontList(label: 'Montagu Slab', font: GoogleFonts.montaguSlab()),
  BaoFontList(label: 'MonteCarlo', font: GoogleFonts.monteCarlo()),
  BaoFontList(label: 'Montez', font: GoogleFonts.montez()),
  BaoFontList(label: 'Montserrat', font: GoogleFonts.montserrat()),
  BaoFontList(label: 'Montserrat Alternates', font: GoogleFonts.montserratAlternates()),
  BaoFontList(label: 'Montserrat Subrayada', font: GoogleFonts.montserratSubrayada()),
  BaoFontList(label: 'Mountains of Christmas', font: GoogleFonts.mountainsOfChristmas()),
  BaoFontList(label: 'Mouse Memoirs', font: GoogleFonts.mouseMemoirs()),
  BaoFontList(label: 'Mr Bedfort', font: GoogleFonts.mrBedfort()),
  BaoFontList(label: 'Mr Dafoe', font: GoogleFonts.mrDafoe()),
  BaoFontList(label: 'Mr De Haviland', font: GoogleFonts.mrDeHaviland()),
  BaoFontList(label: 'Mrs Saint Delafield', font: GoogleFonts.mrsSaintDelafield()),
  BaoFontList(label: 'Mrs Sheppards', font: GoogleFonts.mrsSheppards()),
  BaoFontList(label: 'Mukta', font: GoogleFonts.mukta()),
  BaoFontList(label: 'Mukta Mahee', font: GoogleFonts.muktaMahee()),
  BaoFontList(label: 'Mukta Malar', font: GoogleFonts.muktaMalar()),
  BaoFontList(label: 'Mukta Vaani', font: GoogleFonts.muktaVaani()),
  BaoFontList(label: 'Muli', font: GoogleFonts.muli()),
  BaoFontList(label: 'Mulish', font: GoogleFonts.mulish()),
  BaoFontList(label: 'Murecho', font: GoogleFonts.murecho()),
  BaoFontList(label: 'MuseoModerno', font: GoogleFonts.museoModerno()),
  BaoFontList(label: 'Mystery Quest', font: GoogleFonts.mysteryQuest()),
  BaoFontList(label: 'NTR', font: GoogleFonts.ntr()),
  BaoFontList(label: 'Nanum Brush Script', font: GoogleFonts.nanumBrushScript()),
  BaoFontList(label: 'Nanum Gothic', font: GoogleFonts.nanumGothic()),
  BaoFontList(label: 'Nanum Gothic Coding', font: GoogleFonts.nanumGothicCoding()),
  BaoFontList(label: 'Nanum Myeongjo', font: GoogleFonts.nanumMyeongjo()),
  BaoFontList(label: 'Nanum Pen Script', font: GoogleFonts.nanumPenScript()),
  BaoFontList(label: 'Nerko One', font: GoogleFonts.nerkoOne()),
  BaoFontList(label: 'Neucha', font: GoogleFonts.neucha()),
  BaoFontList(label: 'Neuton', font: GoogleFonts.neuton()),
  BaoFontList(label: 'New Rocker', font: GoogleFonts.newRocker()),
  BaoFontList(label: 'New Tegomin', font: GoogleFonts.newTegomin()),
  BaoFontList(label: 'News Cycle', font: GoogleFonts.newsCycle()),
  BaoFontList(label: 'Niconne', font: GoogleFonts.niconne()),
  BaoFontList(label: 'Niramit', font: GoogleFonts.niramit()),
  BaoFontList(label: 'Nixie One', font: GoogleFonts.nixieOne()),
  BaoFontList(label: 'Nobile', font: GoogleFonts.nobile()),
  BaoFontList(label: 'Norican', font: GoogleFonts.norican()),
  BaoFontList(label: 'Nosifer', font: GoogleFonts.nosifer()),
  BaoFontList(label: 'Notable', font: GoogleFonts.notable()),
  BaoFontList(label: 'Nothing You Could Do', font: GoogleFonts.nothingYouCouldDo()),
  BaoFontList(label: 'Noticia Text', font: GoogleFonts.noticiaText()),
  BaoFontList(label: 'Noto Color Emoji Compat', font: GoogleFonts.notoColorEmojiCompat()),
  BaoFontList(label: 'Noto Kufi Arabic', font: GoogleFonts.notoKufiArabic()),
  BaoFontList(label: 'Noto Music', font: GoogleFonts.notoMusic()),
  BaoFontList(label: 'Noto Naskh Arabic', font: GoogleFonts.notoNaskhArabic()),
  BaoFontList(label: 'Noto Nastaliq Urdu', font: GoogleFonts.notoNastaliqUrdu()),
  BaoFontList(label: 'Noto Rashi Hebrew', font: GoogleFonts.notoRashiHebrew()),
  BaoFontList(label: 'Noto Sans', font: GoogleFonts.notoSans()),
  BaoFontList(label: 'Noto Sans Adlam', font: GoogleFonts.notoSansAdlam()),
  BaoFontList(label: 'Noto Sans Adlam Unjoined', font: GoogleFonts.notoSansAdlamUnjoined()),
  BaoFontList(label: 'Noto Sans Anatolian Hieroglyphs', font: GoogleFonts.notoSansAnatolianHieroglyphs()),
  BaoFontList(label: 'Noto Sans Arabic', font: GoogleFonts.notoSansArabic()),
  BaoFontList(label: 'Noto Sans Armenian', font: GoogleFonts.notoSansArmenian()),
  BaoFontList(label: 'Noto Sans Avestan', font: GoogleFonts.notoSansAvestan()),
  BaoFontList(label: 'Noto Sans Balinese', font: GoogleFonts.notoSansBalinese()),
  BaoFontList(label: 'Noto Sans Bamum', font: GoogleFonts.notoSansBamum()),
  BaoFontList(label: 'Noto Sans Bassa Vah', font: GoogleFonts.notoSansBassaVah()),
  BaoFontList(label: 'Noto Sans Batak', font: GoogleFonts.notoSansBatak()),
  BaoFontList(label: 'Noto Sans Bengali', font: GoogleFonts.notoSansBengali()),
  BaoFontList(label: 'Noto Sans Bhaiksuki', font: GoogleFonts.notoSansBhaiksuki()),
  BaoFontList(label: 'Noto Sans Brahmi', font: GoogleFonts.notoSansBrahmi()),
  BaoFontList(label: 'Noto Sans Buginese', font: GoogleFonts.notoSansBuginese()),
  BaoFontList(label: 'Noto Sans Buhid', font: GoogleFonts.notoSansBuhid()),
  BaoFontList(label: 'Noto Sans Canadian Aboriginal', font: GoogleFonts.notoSansCanadianAboriginal()),
  BaoFontList(label: 'Noto Sans Carian', font: GoogleFonts.notoSansCarian()),
  BaoFontList(label: 'Noto Sans Caucasian Albanian', font: GoogleFonts.notoSansCaucasianAlbanian()),
  BaoFontList(label: 'Noto Sans Chakma', font: GoogleFonts.notoSansChakma()),
  BaoFontList(label: 'Noto Sans Cham', font: GoogleFonts.notoSansCham()),
  BaoFontList(label: 'Noto Sans Cherokee', font: GoogleFonts.notoSansCherokee()),
  BaoFontList(label: 'Noto Sans Coptic', font: GoogleFonts.notoSansCoptic()),
  BaoFontList(label: 'Noto Sans Cuneiform', font: GoogleFonts.notoSansCuneiform()),
  BaoFontList(label: 'Noto Sans Cypriot', font: GoogleFonts.notoSansCypriot()),
  BaoFontList(label: 'Noto Sans Deseret', font: GoogleFonts.notoSansDeseret()),
  BaoFontList(label: 'Noto Sans Devanagari', font: GoogleFonts.notoSansDevanagari()),
  BaoFontList(label: 'Noto Sans Display', font: GoogleFonts.notoSansDisplay()),
  BaoFontList(label: 'Noto Sans Duployan', font: GoogleFonts.notoSansDuployan()),
  BaoFontList(label: 'Noto Sans Egyptian Hieroglyphs', font: GoogleFonts.notoSansEgyptianHieroglyphs()),
  BaoFontList(label: 'Noto Sans Elbasan', font: GoogleFonts.notoSansElbasan()),
  BaoFontList(label: 'Noto Sans Elymaic', font: GoogleFonts.notoSansElymaic()),
  BaoFontList(label: 'Noto Sans Georgian', font: GoogleFonts.notoSansGeorgian()),
  BaoFontList(label: 'Noto Sans Glagolitic', font: GoogleFonts.notoSansGlagolitic()),
  BaoFontList(label: 'Noto Sans Gothic', font: GoogleFonts.notoSansGothic()),
  BaoFontList(label: 'Noto Sans Grantha', font: GoogleFonts.notoSansGrantha()),
  BaoFontList(label: 'Noto Sans Gujarati', font: GoogleFonts.notoSansGujarati()),
  BaoFontList(label: 'Noto Sans Gunjala Gondi', font: GoogleFonts.notoSansGunjalaGondi()),
  BaoFontList(label: 'Noto Sans Gurmukhi', font: GoogleFonts.notoSansGurmukhi()),
  BaoFontList(label: 'Noto Sans Hanifi Rohingya', font: GoogleFonts.notoSansHanifiRohingya()),
  BaoFontList(label: 'Noto Sans Hanunoo', font: GoogleFonts.notoSansHanunoo()),
  BaoFontList(label: 'Noto Sans Hatran', font: GoogleFonts.notoSansHatran()),
  BaoFontList(label: 'Noto Sans Hebrew', font: GoogleFonts.notoSansHebrew()),
  BaoFontList(label: 'Noto Sans Imperial Aramaic', font: GoogleFonts.notoSansImperialAramaic()),
  BaoFontList(label: 'Noto Sans Indic Siyaq Numbers', font: GoogleFonts.notoSansIndicSiyaqNumbers()),
  BaoFontList(label: 'Noto Sans Inscriptional Pahlavi', font: GoogleFonts.notoSansInscriptionalPahlavi()),
  BaoFontList(label: 'Noto Sans Inscriptional Parthian', font: GoogleFonts.notoSansInscriptionalParthian()),
  BaoFontList(label: 'Noto Sans Javanese', font: GoogleFonts.notoSansJavanese()),
  BaoFontList(label: 'Noto Sans Kaithi', font: GoogleFonts.notoSansKaithi()),
  BaoFontList(label: 'Noto Sans Kannada', font: GoogleFonts.notoSansKannada()),
  BaoFontList(label: 'Noto Sans Kayah Li', font: GoogleFonts.notoSansKayahLi()),
  BaoFontList(label: 'Noto Sans Kharoshthi', font: GoogleFonts.notoSansKharoshthi()),
  BaoFontList(label: 'Noto Sans Khmer', font: GoogleFonts.notoSansKhmer()),
  BaoFontList(label: 'Noto Sans Khojki', font: GoogleFonts.notoSansKhojki()),
  BaoFontList(label: 'Noto Sans Khudawadi', font: GoogleFonts.notoSansKhudawadi()),
  BaoFontList(label: 'Noto Sans Lao', font: GoogleFonts.notoSansLao()),
  BaoFontList(label: 'Noto Sans Lepcha', font: GoogleFonts.notoSansLepcha()),
  BaoFontList(label: 'Noto Sans Limbu', font: GoogleFonts.notoSansLimbu()),
  BaoFontList(label: 'Noto Sans Linear A', font: GoogleFonts.notoSansLinearA()),
  BaoFontList(label: 'Noto Sans Linear B', font: GoogleFonts.notoSansLinearB()),
  BaoFontList(label: 'Noto Sans Lisu', font: GoogleFonts.notoSansLisu()),
  BaoFontList(label: 'Noto Sans Lycian', font: GoogleFonts.notoSansLycian()),
  BaoFontList(label: 'Noto Sans Lydian', font: GoogleFonts.notoSansLydian()),
  BaoFontList(label: 'Noto Sans Mahajani', font: GoogleFonts.notoSansMahajani()),
  BaoFontList(label: 'Noto Sans Malayalam', font: GoogleFonts.notoSansMalayalam()),
  BaoFontList(label: 'Noto Sans Mandaic', font: GoogleFonts.notoSansMandaic()),
  BaoFontList(label: 'Noto Sans Manichaean', font: GoogleFonts.notoSansManichaean()),
  BaoFontList(label: 'Noto Sans Marchen', font: GoogleFonts.notoSansMarchen()),
  BaoFontList(label: 'Noto Sans Masaram Gondi', font: GoogleFonts.notoSansMasaramGondi()),
  BaoFontList(label: 'Noto Sans Math', font: GoogleFonts.notoSansMath()),
  BaoFontList(label: 'Noto Sans Mayan Numerals', font: GoogleFonts.notoSansMayanNumerals()),
  BaoFontList(label: 'Noto Sans Medefaidrin', font: GoogleFonts.notoSansMedefaidrin()),
  BaoFontList(label: 'Noto Sans Meetei Mayek', font: GoogleFonts.notoSansMeeteiMayek()),
  BaoFontList(label: 'Noto Sans Meroitic', font: GoogleFonts.notoSansMeroitic()),
  BaoFontList(label: 'Noto Sans Miao', font: GoogleFonts.notoSansMiao()),
  BaoFontList(label: 'Noto Sans Modi', font: GoogleFonts.notoSansModi()),
  BaoFontList(label: 'Noto Sans Mongolian', font: GoogleFonts.notoSansMongolian()),
  BaoFontList(label: 'Noto Sans Mono', font: GoogleFonts.notoSansMono()),
  BaoFontList(label: 'Noto Sans Mro', font: GoogleFonts.notoSansMro()),
  BaoFontList(label: 'Noto Sans Multani', font: GoogleFonts.notoSansMultani()),
  BaoFontList(label: 'Noto Sans Myanmar', font: GoogleFonts.notoSansMyanmar()),
  BaoFontList(label: 'Noto Sans N Ko', font: GoogleFonts.notoSansNKo()),
  BaoFontList(label: 'Noto Sans Nabataean', font: GoogleFonts.notoSansNabataean()),
  BaoFontList(label: 'Noto Sans New Tai Lue', font: GoogleFonts.notoSansNewTaiLue()),
  BaoFontList(label: 'Noto Sans Newa', font: GoogleFonts.notoSansNewa()),
  BaoFontList(label: 'Noto Sans Nushu', font: GoogleFonts.notoSansNushu()),
  BaoFontList(label: 'Noto Sans Ogham', font: GoogleFonts.notoSansOgham()),
  BaoFontList(label: 'Noto Sans Ol Chiki', font: GoogleFonts.notoSansOlChiki()),
  BaoFontList(label: 'Noto Sans Old Hungarian', font: GoogleFonts.notoSansOldHungarian()),
  BaoFontList(label: 'Noto Sans Old Italic', font: GoogleFonts.notoSansOldItalic()),
  BaoFontList(label: 'Noto Sans Old North Arabian', font: GoogleFonts.notoSansOldNorthArabian()),
  BaoFontList(label: 'Noto Sans Old Permic', font: GoogleFonts.notoSansOldPermic()),
  BaoFontList(label: 'Noto Sans Old Persian', font: GoogleFonts.notoSansOldPersian()),
  BaoFontList(label: 'Noto Sans Old Sogdian', font: GoogleFonts.notoSansOldSogdian()),
  BaoFontList(label: 'Noto Sans Old South Arabian', font: GoogleFonts.notoSansOldSouthArabian()),
  BaoFontList(label: 'Noto Sans Old Turkic', font: GoogleFonts.notoSansOldTurkic()),
  BaoFontList(label: 'Noto Sans Oriya', font: GoogleFonts.notoSansOriya()),
  BaoFontList(label: 'Noto Sans Osage', font: GoogleFonts.notoSansOsage()),
  BaoFontList(label: 'Noto Sans Osmanya', font: GoogleFonts.notoSansOsmanya()),
  BaoFontList(label: 'Noto Sans Pahawh Hmong', font: GoogleFonts.notoSansPahawhHmong()),
  BaoFontList(label: 'Noto Sans Palmyrene', font: GoogleFonts.notoSansPalmyrene()),
  BaoFontList(label: 'Noto Sans Pau Cin Hau', font: GoogleFonts.notoSansPauCinHau()),
  BaoFontList(label: 'Noto Sans Phags Pa', font: GoogleFonts.notoSansPhagsPa()),
  BaoFontList(label: 'Noto Sans Phoenician', font: GoogleFonts.notoSansPhoenician()),
  BaoFontList(label: 'Noto Sans Psalter Pahlavi', font: GoogleFonts.notoSansPsalterPahlavi()),
  BaoFontList(label: 'Noto Sans Rejang', font: GoogleFonts.notoSansRejang()),
  BaoFontList(label: 'Noto Sans Runic', font: GoogleFonts.notoSansRunic()),
  BaoFontList(label: 'Noto Sans Samaritan', font: GoogleFonts.notoSansSamaritan()),
  BaoFontList(label: 'Noto Sans Saurashtra', font: GoogleFonts.notoSansSaurashtra()),
  BaoFontList(label: 'Noto Sans Sharada', font: GoogleFonts.notoSansSharada()),
  BaoFontList(label: 'Noto Sans Shavian', font: GoogleFonts.notoSansShavian()),
  BaoFontList(label: 'Noto Sans Siddham', font: GoogleFonts.notoSansSiddham()),
  BaoFontList(label: 'Noto Sans Sinhala', font: GoogleFonts.notoSansSinhala()),
  BaoFontList(label: 'Noto Sans Sogdian', font: GoogleFonts.notoSansSogdian()),
  BaoFontList(label: 'Noto Sans Sora Sompeng', font: GoogleFonts.notoSansSoraSompeng()),
  BaoFontList(label: 'Noto Sans Soyombo', font: GoogleFonts.notoSansSoyombo()),
  BaoFontList(label: 'Noto Sans Sundanese', font: GoogleFonts.notoSansSundanese()),
  BaoFontList(label: 'Noto Sans Syloti Nagri', font: GoogleFonts.notoSansSylotiNagri()),
  BaoFontList(label: 'Noto Sans Symbols', font: GoogleFonts.notoSansSymbols()),
  BaoFontList(label: 'Noto Sans Symbols 2', font: GoogleFonts.notoSansSymbols2()),
  BaoFontList(label: 'Noto Sans Syriac', font: GoogleFonts.notoSansSyriac()),
  BaoFontList(label: 'Noto Sans Tagalog', font: GoogleFonts.notoSansTagalog()),
  BaoFontList(label: 'Noto Sans Tagbanwa', font: GoogleFonts.notoSansTagbanwa()),
  BaoFontList(label: 'Noto Sans Tai Le', font: GoogleFonts.notoSansTaiLe()),
  BaoFontList(label: 'Noto Sans Tai Tham', font: GoogleFonts.notoSansTaiTham()),
  BaoFontList(label: 'Noto Sans Tai Viet', font: GoogleFonts.notoSansTaiViet()),
  BaoFontList(label: 'Noto Sans Takri', font: GoogleFonts.notoSansTakri()),
  BaoFontList(label: 'Noto Sans Tamil', font: GoogleFonts.notoSansTamil()),
  BaoFontList(label: 'Noto Sans Tamil Supplement', font: GoogleFonts.notoSansTamilSupplement()),
  BaoFontList(label: 'Noto Sans Telugu', font: GoogleFonts.notoSansTelugu()),
  BaoFontList(label: 'Noto Sans Thaana', font: GoogleFonts.notoSansThaana()),
  BaoFontList(label: 'Noto Sans Thai', font: GoogleFonts.notoSansThai()),
  BaoFontList(label: 'Noto Sans Thai Looped', font: GoogleFonts.notoSansThaiLooped()),
  BaoFontList(label: 'Noto Sans Tifinagh', font: GoogleFonts.notoSansTifinagh()),
  BaoFontList(label: 'Noto Sans Tirhuta', font: GoogleFonts.notoSansTirhuta()),
  BaoFontList(label: 'Noto Sans Ugaritic', font: GoogleFonts.notoSansUgaritic()),
  BaoFontList(label: 'Noto Sans Vai', font: GoogleFonts.notoSansVai()),
  BaoFontList(label: 'Noto Sans Wancho', font: GoogleFonts.notoSansWancho()),
  BaoFontList(label: 'Noto Sans Warang Citi', font: GoogleFonts.notoSansWarangCiti()),
  BaoFontList(label: 'Noto Sans Yi', font: GoogleFonts.notoSansYi()),
  BaoFontList(label: 'Noto Sans Zanabazar Square', font: GoogleFonts.notoSansZanabazarSquare()),
  BaoFontList(label: 'Noto Serif', font: GoogleFonts.notoSerif()),
  BaoFontList(label: 'Noto Serif Ahom', font: GoogleFonts.notoSerifAhom()),
  BaoFontList(label: 'Noto Serif Armenian', font: GoogleFonts.notoSerifArmenian()),
  BaoFontList(label: 'Noto Serif Balinese', font: GoogleFonts.notoSerifBalinese()),
  BaoFontList(label: 'Noto Serif Bengali', font: GoogleFonts.notoSerifBengali()),
  BaoFontList(label: 'Noto Serif Devanagari', font: GoogleFonts.notoSerifDevanagari()),
  BaoFontList(label: 'Noto Serif Display', font: GoogleFonts.notoSerifDisplay()),
  BaoFontList(label: 'Noto Serif Dogra', font: GoogleFonts.notoSerifDogra()),
  BaoFontList(label: 'Noto Serif Ethiopic', font: GoogleFonts.notoSerifEthiopic()),
  BaoFontList(label: 'Noto Serif Georgian', font: GoogleFonts.notoSerifGeorgian()),
  BaoFontList(label: 'Noto Serif Grantha', font: GoogleFonts.notoSerifGrantha()),
  BaoFontList(label: 'Noto Serif Gujarati', font: GoogleFonts.notoSerifGujarati()),
  BaoFontList(label: 'Noto Serif Gurmukhi', font: GoogleFonts.notoSerifGurmukhi()),
  BaoFontList(label: 'Noto Serif Hebrew', font: GoogleFonts.notoSerifHebrew()),
  BaoFontList(label: 'Noto Serif Kannada', font: GoogleFonts.notoSerifKannada()),
  BaoFontList(label: 'Noto Serif Khmer', font: GoogleFonts.notoSerifKhmer()),
  BaoFontList(label: 'Noto Serif Lao', font: GoogleFonts.notoSerifLao()),
  BaoFontList(label: 'Noto Serif Malayalam', font: GoogleFonts.notoSerifMalayalam()),
  BaoFontList(label: 'Noto Serif Myanmar', font: GoogleFonts.notoSerifMyanmar()),
  BaoFontList(label: 'Noto Serif Nyiakeng Puachue Hmong', font: GoogleFonts.notoSerifNyiakengPuachueHmong()),
  BaoFontList(label: 'Noto Serif Sinhala', font: GoogleFonts.notoSerifSinhala()),
  BaoFontList(label: 'Noto Serif Tamil', font: GoogleFonts.notoSerifTamil()),
  BaoFontList(label: 'Noto Serif Tangut', font: GoogleFonts.notoSerifTangut()),
  BaoFontList(label: 'Noto Serif Telugu', font: GoogleFonts.notoSerifTelugu()),
  BaoFontList(label: 'Noto Serif Thai', font: GoogleFonts.notoSerifThai()),
  BaoFontList(label: 'Noto Serif Tibetan', font: GoogleFonts.notoSerifTibetan()),
  BaoFontList(label: 'Noto Serif Yezidi', font: GoogleFonts.notoSerifYezidi()),
  BaoFontList(label: 'Noto Traditional Nushu', font: GoogleFonts.notoTraditionalNushu()),
  BaoFontList(label: 'Nova Cut', font: GoogleFonts.novaCut()),
  BaoFontList(label: 'Nova Flat', font: GoogleFonts.novaFlat()),
  BaoFontList(label: 'Nova Mono', font: GoogleFonts.novaMono()),
  BaoFontList(label: 'Nova Oval', font: GoogleFonts.novaOval()),
  BaoFontList(label: 'Nova Round', font: GoogleFonts.novaRound()),
  BaoFontList(label: 'Nova Script', font: GoogleFonts.novaScript()),
  BaoFontList(label: 'Nova Slim', font: GoogleFonts.novaSlim()),
  BaoFontList(label: 'Nova Square', font: GoogleFonts.novaSquare()),
  BaoFontList(label: 'Numans', font: GoogleFonts.numans()),
  BaoFontList(label: 'Nunito', font: GoogleFonts.nunito()),
  BaoFontList(label: 'Nunito Sans', font: GoogleFonts.nunitoSans()),
  BaoFontList(label: 'Odibee Sans', font: GoogleFonts.odibeeSans()),
  BaoFontList(label: 'Odor Mean Chey', font: GoogleFonts.odorMeanChey()),
  BaoFontList(label: 'Offside', font: GoogleFonts.offside()),
  BaoFontList(label: 'Oi', font: GoogleFonts.oi()),
  BaoFontList(label: 'Old Standard TT', font: GoogleFonts.oldStandardTt()),
  BaoFontList(label: 'Oldenburg', font: GoogleFonts.oldenburg()),
  BaoFontList(label: 'Oleo Script', font: GoogleFonts.oleoScript()),
  BaoFontList(label: 'Oleo Script Swash Caps', font: GoogleFonts.oleoScriptSwashCaps()),
  BaoFontList(label: 'Open Sans', font: GoogleFonts.openSans()),
  BaoFontList(label: 'Open Sans Condensed', font: GoogleFonts.openSansCondensed()),
  BaoFontList(label: 'Oranienbaum', font: GoogleFonts.oranienbaum()),
  BaoFontList(label: 'Orbitron', font: GoogleFonts.orbitron()),
  BaoFontList(label: 'Oregano', font: GoogleFonts.oregano()),
  BaoFontList(label: 'Orienta', font: GoogleFonts.orienta()),
  BaoFontList(label: 'Original Surfer', font: GoogleFonts.originalSurfer()),
  BaoFontList(label: 'Oswald', font: GoogleFonts.oswald()),
  BaoFontList(label: 'Otomanopee One', font: GoogleFonts.otomanopeeOne()),
  BaoFontList(label: 'Outfit', font: GoogleFonts.outfit()),
  BaoFontList(label: 'Over the Rainbow', font: GoogleFonts.overTheRainbow()),
  BaoFontList(label: 'Overlock', font: GoogleFonts.overlock()),
  BaoFontList(label: 'Overlock SC', font: GoogleFonts.overlockSc()),
  BaoFontList(label: 'Overpass', font: GoogleFonts.overpass()),
  BaoFontList(label: 'Overpass Mono', font: GoogleFonts.overpassMono()),
  BaoFontList(label: 'Ovo', font: GoogleFonts.ovo()),
  BaoFontList(label: 'Oxanium', font: GoogleFonts.oxanium()),
  BaoFontList(label: 'Oxygen', font: GoogleFonts.oxygen()),
  BaoFontList(label: 'Oxygen Mono', font: GoogleFonts.oxygenMono()),
  BaoFontList(label: 'PT Mono', font: GoogleFonts.ptMono()),
  BaoFontList(label: 'PT Sans', font: GoogleFonts.ptSans()),
  BaoFontList(label: 'PT Sans Caption', font: GoogleFonts.ptSansCaption()),
  BaoFontList(label: 'PT Sans Narrow', font: GoogleFonts.ptSansNarrow()),
  BaoFontList(label: 'PT Serif', font: GoogleFonts.ptSerif()),
  BaoFontList(label: 'PT Serif Caption', font: GoogleFonts.ptSerifCaption()),
  BaoFontList(label: 'Pacifico', font: GoogleFonts.pacifico()),
  BaoFontList(label: 'Padauk', font: GoogleFonts.padauk()),
  BaoFontList(label: 'Palanquin', font: GoogleFonts.palanquin()),
  BaoFontList(label: 'Palanquin Dark', font: GoogleFonts.palanquinDark()),
  BaoFontList(label: 'Palette Mosaic', font: GoogleFonts.paletteMosaic()),
  BaoFontList(label: 'Pangolin', font: GoogleFonts.pangolin()),
  BaoFontList(label: 'Paprika', font: GoogleFonts.paprika()),
  BaoFontList(label: 'Parisienne', font: GoogleFonts.parisienne()),
  BaoFontList(label: 'Passero One', font: GoogleFonts.passeroOne()),
  BaoFontList(label: 'Passion One', font: GoogleFonts.passionOne()),
  BaoFontList(label: 'Passions Conflict', font: GoogleFonts.passionsConflict()),
  BaoFontList(label: 'Pathway Gothic One', font: GoogleFonts.pathwayGothicOne()),
  BaoFontList(label: 'Patrick Hand', font: GoogleFonts.patrickHand()),
  BaoFontList(label: 'Patrick Hand SC', font: GoogleFonts.patrickHandSc()),
  BaoFontList(label: 'Pattaya', font: GoogleFonts.pattaya()),
  BaoFontList(label: 'Patua One', font: GoogleFonts.patuaOne()),
  BaoFontList(label: 'Pavanam', font: GoogleFonts.pavanam()),
  BaoFontList(label: 'Paytone One', font: GoogleFonts.paytoneOne()),
  BaoFontList(label: 'Peddana', font: GoogleFonts.peddana()),
  BaoFontList(label: 'Peralta', font: GoogleFonts.peralta()),
  BaoFontList(label: 'Permanent Marker', font: GoogleFonts.permanentMarker()),
  BaoFontList(label: 'Petemoss', font: GoogleFonts.petemoss()),
  BaoFontList(label: 'Petit Formal Script', font: GoogleFonts.petitFormalScript()),
  BaoFontList(label: 'Petrona', font: GoogleFonts.petrona()),
  BaoFontList(label: 'Philosopher', font: GoogleFonts.philosopher()),
  BaoFontList(label: 'Piazzolla', font: GoogleFonts.piazzolla()),
  BaoFontList(label: 'Piedra', font: GoogleFonts.piedra()),
  BaoFontList(label: 'Pinyon Script', font: GoogleFonts.pinyonScript()),
  BaoFontList(label: 'Pirata One', font: GoogleFonts.pirataOne()),
  BaoFontList(label: 'Plaster', font: GoogleFonts.plaster()),
  BaoFontList(label: 'Play', font: GoogleFonts.play()),
  BaoFontList(label: 'Playball', font: GoogleFonts.playball()),
  BaoFontList(label: 'Playfair Display', font: GoogleFonts.playfairDisplay()),
  BaoFontList(label: 'Playfair Display SC', font: GoogleFonts.playfairDisplaySc()),
  BaoFontList(label: 'Podkova', font: GoogleFonts.podkova()),
  BaoFontList(label: 'Poiret One', font: GoogleFonts.poiretOne()),
  BaoFontList(label: 'Poller One', font: GoogleFonts.pollerOne()),
  BaoFontList(label: 'Poly', font: GoogleFonts.poly()),
  BaoFontList(label: 'Pompiere', font: GoogleFonts.pompiere()),
  BaoFontList(label: 'Pontano Sans', font: GoogleFonts.pontanoSans()),
  BaoFontList(label: 'Poor Story', font: GoogleFonts.poorStory()),
  BaoFontList(label: 'Poppins', font: GoogleFonts.poppins()),
  BaoFontList(label: 'Port Lligat Sans', font: GoogleFonts.portLligatSans()),
  BaoFontList(label: 'Port Lligat Slab', font: GoogleFonts.portLligatSlab()),
  BaoFontList(label: 'Potta One', font: GoogleFonts.pottaOne()),
  BaoFontList(label: 'Pragati Narrow', font: GoogleFonts.pragatiNarrow()),
  BaoFontList(label: 'Praise', font: GoogleFonts.praise()),
  BaoFontList(label: 'Prata', font: GoogleFonts.prata()),
  BaoFontList(label: 'Press Start 2P', font: GoogleFonts.pressStart2p()),
  BaoFontList(label: 'Pridi', font: GoogleFonts.pridi()),
  BaoFontList(label: 'Princess Sofia', font: GoogleFonts.princessSofia()),
  BaoFontList(label: 'Prociono', font: GoogleFonts.prociono()),
  BaoFontList(label: 'Prompt', font: GoogleFonts.prompt()),
  BaoFontList(label: 'Prosto One', font: GoogleFonts.prostoOne()),
  BaoFontList(label: 'Proza Libre', font: GoogleFonts.prozaLibre()),
  BaoFontList(label: 'Public Sans', font: GoogleFonts.publicSans()),
  BaoFontList(label: 'Puppies Play', font: GoogleFonts.puppiesPlay()),
  BaoFontList(label: 'Puritan', font: GoogleFonts.puritan()),
  BaoFontList(label: 'Purple Purse', font: GoogleFonts.purplePurse()),
  BaoFontList(label: 'Pushster', font: GoogleFonts.pushster()),
  BaoFontList(label: 'Qahiri', font: GoogleFonts.qahiri()),
  BaoFontList(label: 'Quando', font: GoogleFonts.quando()),
  BaoFontList(label: 'Quantico', font: GoogleFonts.quantico()),
  BaoFontList(label: 'Quattrocento', font: GoogleFonts.quattrocento()),
  BaoFontList(label: 'Quattrocento Sans', font: GoogleFonts.quattrocentoSans()),
  BaoFontList(label: 'Questrial', font: GoogleFonts.questrial()),
  BaoFontList(label: 'Quicksand', font: GoogleFonts.quicksand()),
  BaoFontList(label: 'Quintessential', font: GoogleFonts.quintessential()),
  BaoFontList(label: 'Qwigley', font: GoogleFonts.qwigley()),
  BaoFontList(label: 'Racing Sans One', font: GoogleFonts.racingSansOne()),
  BaoFontList(label: 'Radley', font: GoogleFonts.radley()),
  BaoFontList(label: 'Rajdhani', font: GoogleFonts.rajdhani()),
  BaoFontList(label: 'Rakkas', font: GoogleFonts.rakkas()),
  BaoFontList(label: 'Raleway', font: GoogleFonts.raleway()),
  BaoFontList(label: 'Raleway Dots', font: GoogleFonts.ralewayDots()),
  BaoFontList(label: 'Ramabhadra', font: GoogleFonts.ramabhadra()),
  BaoFontList(label: 'Ramaraja', font: GoogleFonts.ramaraja()),
  BaoFontList(label: 'Rambla', font: GoogleFonts.rambla()),
  BaoFontList(label: 'Rammetto One', font: GoogleFonts.rammettoOne()),
  BaoFontList(label: 'Rampart One', font: GoogleFonts.rampartOne()),
  BaoFontList(label: 'Ranchers', font: GoogleFonts.ranchers()),
  BaoFontList(label: 'Rancho', font: GoogleFonts.rancho()),
  BaoFontList(label: 'Ranga', font: GoogleFonts.ranga()),
  BaoFontList(label: 'Rasa', font: GoogleFonts.rasa()),
  BaoFontList(label: 'Rationale', font: GoogleFonts.rationale()),
  BaoFontList(label: 'Ravi Prakash', font: GoogleFonts.raviPrakash()),
  BaoFontList(label: 'Readex Pro', font: GoogleFonts.readexPro()),
  BaoFontList(label: 'Recursive', font: GoogleFonts.recursive()),
  BaoFontList(label: 'Red Hat Display', font: GoogleFonts.redHatDisplay()),
  BaoFontList(label: 'Red Hat Mono', font: GoogleFonts.redHatMono()),
  BaoFontList(label: 'Red Hat Text', font: GoogleFonts.redHatText()),
  BaoFontList(label: 'Red Rose', font: GoogleFonts.redRose()),
  BaoFontList(label: 'Redacted', font: GoogleFonts.redacted()),
  BaoFontList(label: 'Redacted Script', font: GoogleFonts.redactedScript()),
  BaoFontList(label: 'Redressed', font: GoogleFonts.redressed()),
  BaoFontList(label: 'Reem Kufi', font: GoogleFonts.reemKufi()),
  BaoFontList(label: 'Reenie Beanie', font: GoogleFonts.reenieBeanie()),
  BaoFontList(label: 'Reggae One', font: GoogleFonts.reggaeOne()),
  BaoFontList(label: 'Revalia', font: GoogleFonts.revalia()),
  BaoFontList(label: 'Rhodium Libre', font: GoogleFonts.rhodiumLibre()),
  BaoFontList(label: 'Ribeye', font: GoogleFonts.ribeye()),
  BaoFontList(label: 'Ribeye Marrow', font: GoogleFonts.ribeyeMarrow()),
  BaoFontList(label: 'Righteous', font: GoogleFonts.righteous()),
  BaoFontList(label: 'Risque', font: GoogleFonts.risque()),
  BaoFontList(label: 'Road Rage', font: GoogleFonts.roadRage()),
  BaoFontList(label: 'Roboto', font: GoogleFonts.roboto()),
  BaoFontList(label: 'Roboto Condensed', font: GoogleFonts.robotoCondensed()),
  BaoFontList(label: 'Roboto Mono', font: GoogleFonts.robotoMono()),
  BaoFontList(label: 'Roboto Slab', font: GoogleFonts.robotoSlab()),
  BaoFontList(label: 'Rochester', font: GoogleFonts.rochester()),
  BaoFontList(label: 'Rock 3D', font: GoogleFonts.rock3d()),
  BaoFontList(label: 'Rock Salt', font: GoogleFonts.rockSalt()),
  BaoFontList(label: 'RocknRoll One', font: GoogleFonts.rocknRollOne()),
  BaoFontList(label: 'Rokkitt', font: GoogleFonts.rokkitt()),
  BaoFontList(label: 'Romanesco', font: GoogleFonts.romanesco()),
  BaoFontList(label: 'Ropa Sans', font: GoogleFonts.ropaSans()),
  BaoFontList(label: 'Rosario', font: GoogleFonts.rosario()),
  BaoFontList(label: 'Rosarivo', font: GoogleFonts.rosarivo()),
  BaoFontList(label: 'Rouge Script', font: GoogleFonts.rougeScript()),
  BaoFontList(label: 'Rowdies', font: GoogleFonts.rowdies()),
  BaoFontList(label: 'Rozha One', font: GoogleFonts.rozhaOne()),
  BaoFontList(label: 'Rubik', font: GoogleFonts.rubik()),
  BaoFontList(label: 'Rubik Beastly', font: GoogleFonts.rubikBeastly()),
  BaoFontList(label: 'Rubik Mono One', font: GoogleFonts.rubikMonoOne()),
  BaoFontList(label: 'Ruda', font: GoogleFonts.ruda()),
  BaoFontList(label: 'Rufina', font: GoogleFonts.rufina()),
  BaoFontList(label: 'Ruge Boogie', font: GoogleFonts.rugeBoogie()),
  BaoFontList(label: 'Ruluko', font: GoogleFonts.ruluko()),
  BaoFontList(label: 'Rum Raisin', font: GoogleFonts.rumRaisin()),
  BaoFontList(label: 'Ruslan Display', font: GoogleFonts.ruslanDisplay()),
  BaoFontList(label: 'Russo One', font: GoogleFonts.russoOne()),
  BaoFontList(label: 'Ruthie', font: GoogleFonts.ruthie()),
  BaoFontList(label: 'Rye', font: GoogleFonts.rye()),
  BaoFontList(label: 'STIX Two Text', font: GoogleFonts.stixTwoText()),
  BaoFontList(label: 'Sacramento', font: GoogleFonts.sacramento()),
  BaoFontList(label: 'Sahitya', font: GoogleFonts.sahitya()),
  BaoFontList(label: 'Sail', font: GoogleFonts.sail()),
  BaoFontList(label: 'Saira', font: GoogleFonts.saira()),
  BaoFontList(label: 'Saira Condensed', font: GoogleFonts.sairaCondensed()),
  BaoFontList(label: 'Saira Extra Condensed', font: GoogleFonts.sairaExtraCondensed()),
  BaoFontList(label: 'Saira Semi Condensed', font: GoogleFonts.sairaSemiCondensed()),
  BaoFontList(label: 'Saira Stencil One', font: GoogleFonts.sairaStencilOne()),
  BaoFontList(label: 'Salsa', font: GoogleFonts.salsa()),
  BaoFontList(label: 'Sanchez', font: GoogleFonts.sanchez()),
  BaoFontList(label: 'Sancreek', font: GoogleFonts.sancreek()),
  BaoFontList(label: 'Sansita', font: GoogleFonts.sansita()),
  BaoFontList(label: 'Sansita Swashed', font: GoogleFonts.sansitaSwashed()),
  BaoFontList(label: 'Sarabun', font: GoogleFonts.sarabun()),
  BaoFontList(label: 'Sarala', font: GoogleFonts.sarala()),
  BaoFontList(label: 'Sarina', font: GoogleFonts.sarina()),
  BaoFontList(label: 'Sarpanch', font: GoogleFonts.sarpanch()),
  BaoFontList(label: 'Sassy Frass', font: GoogleFonts.sassyFrass()),
  BaoFontList(label: 'Satisfy', font: GoogleFonts.satisfy()),
  BaoFontList(label: 'Sawarabi Gothic', font: GoogleFonts.sawarabiGothic()),
  BaoFontList(label: 'Sawarabi Mincho', font: GoogleFonts.sawarabiMincho()),
  BaoFontList(label: 'Scada', font: GoogleFonts.scada()),
  BaoFontList(label: 'Scheherazade', font: GoogleFonts.scheherazade()),
  BaoFontList(label: 'Scheherazade New', font: GoogleFonts.scheherazadeNew()),
  BaoFontList(label: 'Schoolbell', font: GoogleFonts.schoolbell()),
  BaoFontList(label: 'Scope One', font: GoogleFonts.scopeOne()),
  BaoFontList(label: 'Seaweed Script', font: GoogleFonts.seaweedScript()),
  BaoFontList(label: 'Secular One', font: GoogleFonts.secularOne()),
  BaoFontList(label: 'Sedgwick Ave', font: GoogleFonts.sedgwickAve()),
  BaoFontList(label: 'Sedgwick Ave Display', font: GoogleFonts.sedgwickAveDisplay()),
  BaoFontList(label: 'Sen', font: GoogleFonts.sen()),
  BaoFontList(label: 'Sevillana', font: GoogleFonts.sevillana()),
  BaoFontList(label: 'Seymour One', font: GoogleFonts.seymourOne()),
  BaoFontList(label: 'Shadows Into Light', font: GoogleFonts.shadowsIntoLight()),
  BaoFontList(label: 'Shadows Into Light Two', font: GoogleFonts.shadowsIntoLightTwo()),
  BaoFontList(label: 'Shalimar', font: GoogleFonts.shalimar()),
  BaoFontList(label: 'Shanti', font: GoogleFonts.shanti()),
  BaoFontList(label: 'Share', font: GoogleFonts.share()),
  BaoFontList(label: 'Share Tech', font: GoogleFonts.shareTech()),
  BaoFontList(label: 'Share Tech Mono', font: GoogleFonts.shareTechMono()),
  BaoFontList(label: 'Shippori Antique', font: GoogleFonts.shipporiAntique()),
  BaoFontList(label: 'Shippori Antique B1', font: GoogleFonts.shipporiAntiqueB1()),
  BaoFontList(label: 'Shippori Mincho', font: GoogleFonts.shipporiMincho()),
  BaoFontList(label: 'Shippori Mincho B1', font: GoogleFonts.shipporiMinchoB1()),
  BaoFontList(label: 'Shizuru', font: GoogleFonts.shizuru()),
  BaoFontList(label: 'Shojumaru', font: GoogleFonts.shojumaru()),
  BaoFontList(label: 'Short Stack', font: GoogleFonts.shortStack()),
  BaoFontList(label: 'Shrikhand', font: GoogleFonts.shrikhand()),
  BaoFontList(label: 'Sigmar One', font: GoogleFonts.sigmarOne()),
  BaoFontList(label: 'Signika', font: GoogleFonts.signika()),
  BaoFontList(label: 'Signika Negative', font: GoogleFonts.signikaNegative()),
  BaoFontList(label: 'Simonetta', font: GoogleFonts.simonetta()),
  BaoFontList(label: 'Single Day', font: GoogleFonts.singleDay()),
  BaoFontList(label: 'Sintony', font: GoogleFonts.sintony()),
  BaoFontList(label: 'Sirin Stencil', font: GoogleFonts.sirinStencil()),
  BaoFontList(label: 'Six Caps', font: GoogleFonts.sixCaps()),
  BaoFontList(label: 'Skranji', font: GoogleFonts.skranji()),
  BaoFontList(label: 'Slabo 13px', font: GoogleFonts.slabo13px()),
  BaoFontList(label: 'Slabo 27px', font: GoogleFonts.slabo27px()),
  BaoFontList(label: 'Slackey', font: GoogleFonts.slackey()),
  BaoFontList(label: 'Smokum', font: GoogleFonts.smokum()),
  BaoFontList(label: 'Smooch', font: GoogleFonts.smooch()),
  BaoFontList(label: 'Smythe', font: GoogleFonts.smythe()),
  BaoFontList(label: 'Sniglet', font: GoogleFonts.sniglet()),
  BaoFontList(label: 'Snippet', font: GoogleFonts.snippet()),
  BaoFontList(label: 'Snowburst One', font: GoogleFonts.snowburstOne()),
  BaoFontList(label: 'Sofadi One', font: GoogleFonts.sofadiOne()),
  BaoFontList(label: 'Sofia', font: GoogleFonts.sofia()),
  BaoFontList(label: 'Solway', font: GoogleFonts.solway()),
  BaoFontList(label: 'Song Myung', font: GoogleFonts.songMyung()),
  BaoFontList(label: 'Sonsie One', font: GoogleFonts.sonsieOne()),
  BaoFontList(label: 'Sora', font: GoogleFonts.sora()),
  BaoFontList(label: 'Sorts Mill Goudy', font: GoogleFonts.sortsMillGoudy()),
  BaoFontList(label: 'Source Code Pro', font: GoogleFonts.sourceCodePro()),
  BaoFontList(label: 'Source Sans 3', font: GoogleFonts.sourceSans3()),
  BaoFontList(label: 'Source Sans Pro', font: GoogleFonts.sourceSansPro()),
  BaoFontList(label: 'Source Serif Pro', font: GoogleFonts.sourceSerifPro()),
  BaoFontList(label: 'Space Grotesk', font: GoogleFonts.spaceGrotesk()),
  BaoFontList(label: 'Space Mono', font: GoogleFonts.spaceMono()),
  BaoFontList(label: 'Spartan', font: GoogleFonts.spartan()),
  BaoFontList(label: 'Special Elite', font: GoogleFonts.specialElite()),
  BaoFontList(label: 'Spectral', font: GoogleFonts.spectral()),
  BaoFontList(label: 'Spectral SC', font: GoogleFonts.spectralSc()),
  BaoFontList(label: 'Spicy Rice', font: GoogleFonts.spicyRice()),
  BaoFontList(label: 'Spinnaker', font: GoogleFonts.spinnaker()),
  BaoFontList(label: 'Spirax', font: GoogleFonts.spirax()),
  BaoFontList(label: 'Squada One', font: GoogleFonts.squadaOne()),
  BaoFontList(label: 'Sree Krushnadevaraya', font: GoogleFonts.sreeKrushnadevaraya()),
  BaoFontList(label: 'Sriracha', font: GoogleFonts.sriracha()),
  BaoFontList(label: 'Srisakdi', font: GoogleFonts.srisakdi()),
  BaoFontList(label: 'Staatliches', font: GoogleFonts.staatliches()),
  BaoFontList(label: 'Stalemate', font: GoogleFonts.stalemate()),
  BaoFontList(label: 'Stalinist One', font: GoogleFonts.stalinistOne()),
  BaoFontList(label: 'Stardos Stencil', font: GoogleFonts.stardosStencil()),
  BaoFontList(label: 'Stick', font: GoogleFonts.stick()),
  BaoFontList(label: 'Stick No Bills', font: GoogleFonts.stickNoBills()),
  BaoFontList(label: 'Stint Ultra Condensed', font: GoogleFonts.stintUltraCondensed()),
  BaoFontList(label: 'Stint Ultra Expanded', font: GoogleFonts.stintUltraExpanded()),
  BaoFontList(label: 'Stoke', font: GoogleFonts.stoke()),
  BaoFontList(label: 'Strait', font: GoogleFonts.strait()),
  BaoFontList(label: 'Style Script', font: GoogleFonts.styleScript()),
  BaoFontList(label: 'Stylish', font: GoogleFonts.stylish()),
  BaoFontList(label: 'Sue Ellen Francisco', font: GoogleFonts.sueEllenFrancisco()),
  BaoFontList(label: 'Suez One', font: GoogleFonts.suezOne()),
  BaoFontList(label: 'Sulphur Point', font: GoogleFonts.sulphurPoint()),
  BaoFontList(label: 'Sumana', font: GoogleFonts.sumana()),
  BaoFontList(label: 'Sunflower', font: GoogleFonts.sunflower()),
  BaoFontList(label: 'Sunshiney', font: GoogleFonts.sunshiney()),
  BaoFontList(label: 'Supermercado One', font: GoogleFonts.supermercadoOne()),
  BaoFontList(label: 'Sura', font: GoogleFonts.sura()),
  BaoFontList(label: 'Suranna', font: GoogleFonts.suranna()),
  BaoFontList(label: 'Suravaram', font: GoogleFonts.suravaram()),
  BaoFontList(label: 'Swanky and Moo Moo', font: GoogleFonts.swankyAndMooMoo()),
  BaoFontList(label: 'Syncopate', font: GoogleFonts.syncopate()),
  BaoFontList(label: 'Syne', font: GoogleFonts.syne()),
  BaoFontList(label: 'Syne Mono', font: GoogleFonts.syneMono()),
  BaoFontList(label: 'Syne Tactile', font: GoogleFonts.syneTactile()),
  BaoFontList(label: 'Tajawal', font: GoogleFonts.tajawal()),
  BaoFontList(label: 'Tangerine', font: GoogleFonts.tangerine()),
  BaoFontList(label: 'Tauri', font: GoogleFonts.tauri()),
  BaoFontList(label: 'Taviraj', font: GoogleFonts.taviraj()),
  BaoFontList(label: 'Teko', font: GoogleFonts.teko()),
  BaoFontList(label: 'Telex', font: GoogleFonts.telex()),
  BaoFontList(label: 'Tenali Ramakrishna', font: GoogleFonts.tenaliRamakrishna()),
  BaoFontList(label: 'Tenor Sans', font: GoogleFonts.tenorSans()),
  BaoFontList(label: 'Text Me One', font: GoogleFonts.textMeOne()),
  BaoFontList(label: 'Thasadith', font: GoogleFonts.thasadith()),
  BaoFontList(label: 'The Girl Next Door', font: GoogleFonts.theGirlNextDoor()),
  BaoFontList(label: 'Tienne', font: GoogleFonts.tienne()),
  BaoFontList(label: 'Tillana', font: GoogleFonts.tillana()),
  BaoFontList(label: 'Timmana', font: GoogleFonts.timmana()),
  BaoFontList(label: 'Tinos', font: GoogleFonts.tinos()),
  BaoFontList(label: 'Titan One', font: GoogleFonts.titanOne()),
  BaoFontList(label: 'Titillium Web', font: GoogleFonts.titilliumWeb()),
  BaoFontList(label: 'Tomorrow', font: GoogleFonts.tomorrow()),
  BaoFontList(label: 'Tourney', font: GoogleFonts.tourney()),
  BaoFontList(label: 'Trade Winds', font: GoogleFonts.tradeWinds()),
  BaoFontList(label: 'Train One', font: GoogleFonts.trainOne()),
  BaoFontList(label: 'Trirong', font: GoogleFonts.trirong()),
  BaoFontList(label: 'Trispace', font: GoogleFonts.trispace()),
  BaoFontList(label: 'Trocchi', font: GoogleFonts.trocchi()),
  BaoFontList(label: 'Trochut', font: GoogleFonts.trochut()),
  BaoFontList(label: 'Trykker', font: GoogleFonts.trykker()),
  BaoFontList(label: 'Tulpen One', font: GoogleFonts.tulpenOne()),
  BaoFontList(label: 'Turret Road', font: GoogleFonts.turretRoad()),
  BaoFontList(label: 'Ubuntu', font: GoogleFonts.ubuntu()),
  BaoFontList(label: 'Ubuntu Condensed', font: GoogleFonts.ubuntuCondensed()),
  BaoFontList(label: 'Ubuntu Mono', font: GoogleFonts.ubuntuMono()),
  BaoFontList(label: 'Uchen', font: GoogleFonts.uchen()),
  BaoFontList(label: 'Ultra', font: GoogleFonts.ultra()),
  BaoFontList(label: 'Uncial Antiqua', font: GoogleFonts.uncialAntiqua()),
  BaoFontList(label: 'Underdog', font: GoogleFonts.underdog()),
  BaoFontList(label: 'Unica One', font: GoogleFonts.unicaOne()),
  BaoFontList(label: 'UnifrakturCook', font: GoogleFonts.unifrakturCook()),
  BaoFontList(label: 'UnifrakturMaguntia', font: GoogleFonts.unifrakturMaguntia()),
  BaoFontList(label: 'Unkempt', font: GoogleFonts.unkempt()),
  BaoFontList(label: 'Unlock', font: GoogleFonts.unlock()),
  BaoFontList(label: 'Unna', font: GoogleFonts.unna()),
  BaoFontList(label: 'Urbanist', font: GoogleFonts.urbanist()),
  BaoFontList(label: 'VT323', font: GoogleFonts.vt323()),
  BaoFontList(label: 'Vampiro One', font: GoogleFonts.vampiroOne()),
  BaoFontList(label: 'Varela', font: GoogleFonts.varela()),
  BaoFontList(label: 'Varela Round', font: GoogleFonts.varelaRound()),
  BaoFontList(label: 'Varta', font: GoogleFonts.varta()),
  BaoFontList(label: 'Vast Shadow', font: GoogleFonts.vastShadow()),
  BaoFontList(label: 'Vesper Libre', font: GoogleFonts.vesperLibre()),
  BaoFontList(label: 'Viaoda Libre', font: GoogleFonts.viaodaLibre()),
  BaoFontList(label: 'Vibes', font: GoogleFonts.vibes()),
  BaoFontList(label: 'Vibur', font: GoogleFonts.vibur()),
  BaoFontList(label: 'Vidaloka', font: GoogleFonts.vidaloka()),
  BaoFontList(label: 'Viga', font: GoogleFonts.viga()),
  BaoFontList(label: 'Voces', font: GoogleFonts.voces()),
  BaoFontList(label: 'Volkhov', font: GoogleFonts.volkhov()),
  BaoFontList(label: 'Vollkorn', font: GoogleFonts.vollkorn()),
  BaoFontList(label: 'Vollkorn SC', font: GoogleFonts.vollkornSc()),
  BaoFontList(label: 'Voltaire', font: GoogleFonts.voltaire()),
  BaoFontList(label: 'Waiting for the Sunrise', font: GoogleFonts.waitingForTheSunrise()),
  BaoFontList(label: 'Wallpoet', font: GoogleFonts.wallpoet()),
  BaoFontList(label: 'Walter Turncoat', font: GoogleFonts.walterTurncoat()),
  BaoFontList(label: 'Warnes', font: GoogleFonts.warnes()),
  BaoFontList(label: 'Wellfleet', font: GoogleFonts.wellfleet()),
  BaoFontList(label: 'Wendy One', font: GoogleFonts.wendyOne()),
  BaoFontList(label: 'WindSong', font: GoogleFonts.windSong()),
  BaoFontList(label: 'Wire One', font: GoogleFonts.wireOne()),
  BaoFontList(label: 'Work Sans', font: GoogleFonts.workSans()),
  BaoFontList(label: 'Xanh Mono', font: GoogleFonts.xanhMono()),
  BaoFontList(label: 'Yaldevi', font: GoogleFonts.yaldevi()),
  BaoFontList(label: 'Yanone Kaffeesatz', font: GoogleFonts.yanoneKaffeesatz()),
  BaoFontList(label: 'Yantramanav', font: GoogleFonts.yantramanav()),
  BaoFontList(label: 'Yatra One', font: GoogleFonts.yatraOne()),
  BaoFontList(label: 'Yellowtail', font: GoogleFonts.yellowtail()),
  BaoFontList(label: 'Yeon Sung', font: GoogleFonts.yeonSung()),
  BaoFontList(label: 'Yeseva One', font: GoogleFonts.yesevaOne()),
  BaoFontList(label: 'Yesteryear', font: GoogleFonts.yesteryear()),
  BaoFontList(label: 'Yomogi', font: GoogleFonts.yomogi()),
  BaoFontList(label: 'Yrsa', font: GoogleFonts.yrsa()),
  BaoFontList(label: 'Yuji Boku', font: GoogleFonts.yujiBoku()),
  BaoFontList(label: 'Yuji Hentaigana Akari', font: GoogleFonts.yujiHentaiganaAkari()),
  BaoFontList(label: 'Yuji Hentaigana Akebono', font: GoogleFonts.yujiHentaiganaAkebono()),
  BaoFontList(label: 'Yuji Mai', font: GoogleFonts.yujiMai()),
  BaoFontList(label: 'Yuji Syuku', font: GoogleFonts.yujiSyuku()),
  BaoFontList(label: 'Yusei Magic', font: GoogleFonts.yuseiMagic()),
  BaoFontList(label: 'ZCOOL KuaiLe', font: GoogleFonts.zcoolKuaiLe()),
  BaoFontList(label: 'ZCOOL QingKe HuangYou', font: GoogleFonts.zcoolQingKeHuangYou()),
  BaoFontList(label: 'ZCOOL XiaoWei', font: GoogleFonts.zcoolXiaoWei()),
  BaoFontList(label: 'Zen Antique', font: GoogleFonts.zenAntique()),
  BaoFontList(label: 'Zen Antique Soft', font: GoogleFonts.zenAntiqueSoft()),
  BaoFontList(label: 'Zen Kaku Gothic Antique', font: GoogleFonts.zenKakuGothicAntique()),
  BaoFontList(label: 'Zen Kaku Gothic New', font: GoogleFonts.zenKakuGothicNew()),
  BaoFontList(label: 'Zen Kurenaido', font: GoogleFonts.zenKurenaido()),
  BaoFontList(label: 'Zen Loop', font: GoogleFonts.zenLoop()),
  BaoFontList(label: 'Zen Maru Gothic', font: GoogleFonts.zenMaruGothic()),
  BaoFontList(label: 'Zen Old Mincho', font: GoogleFonts.zenOldMincho()),
  BaoFontList(label: 'Zen Tokyo Zoo', font: GoogleFonts.zenTokyoZoo()),
  BaoFontList(label: 'Zeyada', font: GoogleFonts.zeyada()),
  BaoFontList(label: 'Zhi Mang Xing', font: GoogleFonts.zhiMangXing()),
  BaoFontList(label: 'Zilla Slab', font: GoogleFonts.zillaSlab()),
  BaoFontList(label: 'Zilla Slab Highlight', font: GoogleFonts.zillaSlabHighlight()),
];
